+ source /root/mugen/libs/locallibs/common_lib.sh
++ python3 --version
++ '[' 0 -eq 0 ']'
++ source /root/mugen/libs/locallibs/common_lib_python.sh
+ source ./common/common_lib.sh
++ source /root/mugen/libs/locallibs/common_lib.sh
+++ python3 --version
+++ '[' 0 -eq 0 ']'
+++ source /root/mugen/libs/locallibs/common_lib_python.sh
++ ARRAY_PROFILE=("arm-native-android-container-robox" "basic-test-suite-baseline-fio" "basic-test-suite-baseline-lmbench" "basic-test-suite-baseline-netperf" "basic-test-suite-baseline-stream" "basic-test-suite-baseline-unixbench" "basic-test-suite-speccpu-speccpu2006" "basic-test-suite-specjbb-specjbb2015" "big-data-hadoop-hdfs-dfsio-hdd" "big-data-hadoop-hdfs-dfsio-ssd" "big-data-hadoop-spark-bayesian" "big-data-hadoop-spark-kmeans" "big-data-hadoop-spark-sql1" "big-data-hadoop-spark-sql10" "big-data-hadoop-spark-sql2" "big-data-hadoop-spark-sql3" "big-data-hadoop-spark-sql4" "big-data-hadoop-spark-sql5" "big-data-hadoop-spark-sql6" "big-data-hadoop-spark-sql7" "big-data-hadoop-spark-sql8" "big-data-hadoop-spark-sql9" "big-data-hadoop-spark-tersort" "big-data-hadoop-spark-wordcount" "cloud-compute-kvm-host" "database-mariadb-2p-tpcc-c3" "database-mariadb-4p-tpcc-c3" "database-mongodb-2p-sysbench" "database-mysql-2p-sysbench-hdd" "database-mysql-2p-sysbench-ssd" "database-postgresql-2p-sysbench-hdd" "database-postgresql-2p-sysbench-ssd" "default-default" "docker-mariadb-2p-tpcc-c3" "docker-mariadb-4p-tpcc-c3" "hpc-gatk4-human-genome" "in-memory-database-redis-redis-benchmark" "middleware-dubbo-dubbo-benchmark" "storage-ceph-vdbench-hdd" "storage-ceph-vdbench-ssd" "virtualization-consumer-cloud-olc" "virtualization-mariadb-2p-tpcc-c3" "virtualization-mariadb-4p-tpcc-c3" "web-apache-traffic-server-spirent-pingpo" "web-nginx-http-long-connection" "web-nginx-https-short-connection")
++ ARRAY_SERVICE=("arm-native" "basic-test-suite" "big-data" "cloud-compute" "database" "default" "docker" "hpc" "in-memory-database" "middleware" "storage" "virtualization" "web")
++ SPECIAL_CHARACTERS='~\!@#%^*'
++ ULTRA_LONG_CHARACTERS=0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
+ main
++ type -t post_test
+ '[' -n function ']'
+ trap post_test EXIT INT HUP TERM
+ rpm -qa
+ grep expect
++ type -t config_params
+ '[' -n '' ']'
++ type -t pre_test
+ '[' -n function ']'
+ pre_test
+ LOG_INFO 'Start environment preparation.'
+ message='Start environment preparation.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start environment preparation.'
Thu May 25 23:03:24 2023 - INFO  - Start environment preparation.
+ deploy_autund
+ DNF_INSTALL 'atune  atune-engine'
+ pkgs='atune  atune-engine'
+ node=1
+ '[' -z '' ']'
+ tmpfile=
++ python3 /root/mugen/libs/locallibs/rpm_manage.py install --pkgs 'atune  atune-engine' --node 1 --tempfile ''
+ tmpfile2=/tmp/tmpntglxwoi
+ '[' -z '' ']'
+ tmpfile=/tmp/tmpntglxwoi
++ lsblk
++ grep disk
++ awk 'NR==1{print $1}'
+ disk_name=vda
+ cp /etc/atuned/atuned.cnf /etc/atuned/atuned.cnf.bak
+ cp /etc/atuned/engine.cnf /etc/atuned/engine.cnf.bak
+ sed -i 's/^disk =.*/disk = vda/g' /etc/atuned/atuned.cnf
+ sed -i 's/^network =.*/network = /g' /etc/atuned/atuned.cnf
+ sed -i 's/rest_tls = true/rest_tls = false/g' /etc/atuned/atuned.cnf
+ sed -i 's/engine_tls = true/engine_tls = false/g' /etc/atuned/atuned.cnf
+ sed -i 's/engine_tls = true/engine_tls = false/g' /etc/atuned/engine.cnf
+ creat_ca
+ CERT_PATH=demo
+ mkdir demo
mkdir: cannot create directory ‘demo’: File exists
+ openssl genrsa -out demo/ca.key 2048
+ openssl req -new -x509 -days 3650 -subj /CN=ca -key demo/ca.key -out demo/ca.crt
+ IP_ADDR=localhost
+ openssl genrsa -out demo/server.key 2048
+ cp /etc/pki/tls/openssl.cnf demo
+ test localhost == localhost
+ echo '[SAN]\nsubjectAltName=DNS:localhost'
+ echo subjectAltName=DNS:localhost
+ openssl req -new -subj /CN=localhost -config demo/openssl.cnf -key demo/server.key -out demo/server.csr
+ openssl x509 -req -sha256 -CA demo/ca.crt -CAkey demo/ca.key -CAcreateserial -days 3650 -extfile demo/extfile.cnf -in demo/server.csr -out demo/server.crt
Certificate request self-signature ok
subject=CN = localhost
+ rm -rf demo/ca.srl demo/server.csr demo/extfile.cnf demo/openssl.cnf
+ IP_ADDR=localhost
+ openssl genrsa -out demo/client.key 2048
+ cp /etc/pki/tls/openssl.cnf demo
+ test localhost == localhost
+ echo '[SAN]\nsubjectAltName=DNS:localhost'
+ echo subjectAltName=DNS:localhost
+ openssl req -new -subj /CN=localhost -config demo/openssl.cnf -key demo/client.key -out demo/client.csr
+ openssl x509 -req -sha256 -CA demo/ca.crt -CAkey demo/ca.key -CAcreateserial -days 3650 -extfile demo/extfile.cnf -in demo/client.csr -out demo/client.crt
Certificate request self-signature ok
subject=CN = localhost
+ rm -rf demo/ca.srl demo/client.csr demo/extfile.cnf demo/openssl.cnf
++ pwd
+ cp -ar /root/mugen/testcases/cli-test/atune/demo/ca.crt demo/server.crt demo/server.key /etc/atuned/rest_certs/
++ pwd
+ cp -ar /root/mugen/testcases/cli-test/atune/demo/ca.crt demo/client.crt demo/client.key /etc/atuned/engine_certs/
++ pwd
+ cp -ar /root/mugen/testcases/cli-test/atune/demo/ca.crt demo/server.crt demo/server.key /etc/atuned/engine_certs/
+ systemctl start atuned
Job for atuned.service failed because the control process exited with error code.
See "systemctl status atuned.service" and "journalctl -xeu atuned.service" for details.
+ grep running
+ systemctl status atuned
+ CHECK_RESULT 1 0 0 'atuned service startup failure'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='atuned service startup failure'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'atuned service startup failure'
+ LOG_ERROR 'atuned service startup failure'
+ message='atuned service startup failure'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'atuned service startup failure'
Thu May 25 23:08:04 2023 - ERROR - atuned service startup failure
+ (( exec_result++ ))
+ LOG_ERROR './common/common_lib.sh line 40'
+ message='./common/common_lib.sh line 40'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message './common/common_lib.sh line 40'
Thu May 25 23:08:04 2023 - ERROR - ./common/common_lib.sh line 40
+ '[' 0 -eq 1 ']'
+ return 0
+ systemctl start atune-engine
+ systemctl status atune-engine
+ grep running
     Active: active (running) since Thu 2023-05-25 23:08:04 CST; 200ms ago
+ CHECK_RESULT 0 0 0 'atune-engine service startup failure'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='atune-engine service startup failure'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ LOG_INFO 'End of environmental preparation!'
+ message='End of environmental preparation!'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End of environmental preparation!'
Thu May 25 23:08:05 2023 - INFO  - End of environmental preparation!
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ (( i=0 ))
+ (( i<46 ))
+ atune-adm profile arm-native-android-container-robox
+ CHECK_RESULT 1 0 0 'atune-adm profile failure'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='atune-adm profile failure'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'atune-adm profile failure'
+ LOG_ERROR 'atune-adm profile failure'
+ message='atune-adm profile failure'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'atune-adm profile failure'
Thu May 25 23:08:06 2023 - ERROR - atune-adm profile failure
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_09.sh line 32'
+ message='oe_test_service_atuned_09.sh line 32'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_09.sh line 32'
Thu May 25 23:08:06 2023 - ERROR - oe_test_service_atuned_09.sh line 32
+ '[' 0 -eq 1 ']'
+ return 0
+ grep -i 'load profile arm-native-android-container-robox Faild' temp.log
+ CHECK_RESULT 1 0 1 'load profile exist'
+ actual_result=1
+ expect_result=0
+ mode=1
+ error_log='load profile exist'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 1 -eq 0 ']'
+ test 1x == 0x
+ return 0
+ atune-adm list
failed to dial "/var/run/atuned/atuned.sock" : connection error: desc = "transport: error while dialing: dial unix /var/run/atuned/atuned.sock: connect: connection refused"
+ grep arm-native-android-container-robox temp.log
+ grep true
+ CHECK_RESULT 1 0 0 'ARRAY_PROFILE not found'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='ARRAY_PROFILE not found'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'ARRAY_PROFILE not found'
+ LOG_ERROR 'ARRAY_PROFILE not found'
+ message='ARRAY_PROFILE not found'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'ARRAY_PROFILE not found'
Thu May 25 23:08:07 2023 - ERROR - ARRAY_PROFILE not found
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_09.sh line 37'
+ message='oe_test_service_atuned_09.sh line 37'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_09.sh line 37'
Thu May 25 23:08:08 2023 - ERROR - oe_test_service_atuned_09.sh line 37
+ '[' 0 -eq 1 ']'
+ return 0
+ (( i++ ))
+ (( i<46 ))
+ atune-adm profile basic-test-suite-baseline-fio
+ CHECK_RESULT 1 0 0 'atune-adm profile failure'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='atune-adm profile failure'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'atune-adm profile failure'
+ LOG_ERROR 'atune-adm profile failure'
+ message='atune-adm profile failure'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'atune-adm profile failure'
Thu May 25 23:08:09 2023 - ERROR - atune-adm profile failure
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_09.sh line 32'
+ message='oe_test_service_atuned_09.sh line 32'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_09.sh line 32'
Thu May 25 23:08:09 2023 - ERROR - oe_test_service_atuned_09.sh line 32
+ '[' 0 -eq 1 ']'
+ return 0
+ grep -i 'load profile basic-test-suite-baseline-fio Faild' temp.log
+ CHECK_RESULT 1 0 1 'load profile exist'
+ actual_result=1
+ expect_result=0
+ mode=1
+ error_log='load profile exist'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 1 -eq 0 ']'
+ test 1x == 0x
+ return 0
+ atune-adm list
failed to dial "/var/run/atuned/atuned.sock" : connection error: desc = "transport: error while dialing: dial unix /var/run/atuned/atuned.sock: connect: connection refused"
+ grep basic-test-suite-baseline-fio temp.log
+ grep true
+ CHECK_RESULT 1 0 0 'ARRAY_PROFILE not found'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='ARRAY_PROFILE not found'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'ARRAY_PROFILE not found'
+ LOG_ERROR 'ARRAY_PROFILE not found'
+ message='ARRAY_PROFILE not found'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'ARRAY_PROFILE not found'
Thu May 25 23:08:10 2023 - ERROR - ARRAY_PROFILE not found
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_09.sh line 37'
+ message='oe_test_service_atuned_09.sh line 37'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_09.sh line 37'
Thu May 25 23:08:11 2023 - ERROR - oe_test_service_atuned_09.sh line 37
+ '[' 0 -eq 1 ']'
+ return 0
+ (( i++ ))
+ (( i<46 ))
+ atune-adm profile basic-test-suite-baseline-lmbench
+ CHECK_RESULT 1 0 0 'atune-adm profile failure'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='atune-adm profile failure'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'atune-adm profile failure'
+ LOG_ERROR 'atune-adm profile failure'
+ message='atune-adm profile failure'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'atune-adm profile failure'
Thu May 25 23:08:12 2023 - ERROR - atune-adm profile failure
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_09.sh line 32'
+ message='oe_test_service_atuned_09.sh line 32'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_09.sh line 32'
Thu May 25 23:08:12 2023 - ERROR - oe_test_service_atuned_09.sh line 32
+ '[' 0 -eq 1 ']'
+ return 0
+ grep -i 'load profile basic-test-suite-baseline-lmbench Faild' temp.log
+ CHECK_RESULT 1 0 1 'load profile exist'
+ actual_result=1
+ expect_result=0
+ mode=1
+ error_log='load profile exist'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 1 -eq 0 ']'
+ test 1x == 0x
+ return 0
+ atune-adm list
failed to dial "/var/run/atuned/atuned.sock" : connection error: desc = "transport: error while dialing: dial unix /var/run/atuned/atuned.sock: connect: connection refused"
+ grep basic-test-suite-baseline-lmbench temp.log
+ grep true
+ CHECK_RESULT 1 0 0 'ARRAY_PROFILE not found'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='ARRAY_PROFILE not found'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'ARRAY_PROFILE not found'
+ LOG_ERROR 'ARRAY_PROFILE not found'
+ message='ARRAY_PROFILE not found'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'ARRAY_PROFILE not found'
Thu May 25 23:08:13 2023 - ERROR - ARRAY_PROFILE not found
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_09.sh line 37'
+ message='oe_test_service_atuned_09.sh line 37'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_09.sh line 37'
Thu May 25 23:08:13 2023 - ERROR - oe_test_service_atuned_09.sh line 37
+ '[' 0 -eq 1 ']'
+ return 0
+ (( i++ ))
+ (( i<46 ))
+ atune-adm profile basic-test-suite-baseline-netperf
+ CHECK_RESULT 1 0 0 'atune-adm profile failure'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='atune-adm profile failure'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'atune-adm profile failure'
+ LOG_ERROR 'atune-adm profile failure'
+ message='atune-adm profile failure'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'atune-adm profile failure'
Thu May 25 23:08:14 2023 - ERROR - atune-adm profile failure
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_09.sh line 32'
+ message='oe_test_service_atuned_09.sh line 32'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_09.sh line 32'
Thu May 25 23:08:15 2023 - ERROR - oe_test_service_atuned_09.sh line 32
+ '[' 0 -eq 1 ']'
+ return 0
+ grep -i 'load profile basic-test-suite-baseline-netperf Faild' temp.log
+ CHECK_RESULT 1 0 1 'load profile exist'
+ actual_result=1
+ expect_result=0
+ mode=1
+ error_log='load profile exist'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 1 -eq 0 ']'
+ test 1x == 0x
+ return 0
+ atune-adm list
failed to dial "/var/run/atuned/atuned.sock" : connection error: desc = "transport: error while dialing: dial unix /var/run/atuned/atuned.sock: connect: connection refused"
+ grep basic-test-suite-baseline-netperf temp.log
+ grep true
+ CHECK_RESULT 1 0 0 'ARRAY_PROFILE not found'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='ARRAY_PROFILE not found'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'ARRAY_PROFILE not found'
+ LOG_ERROR 'ARRAY_PROFILE not found'
+ message='ARRAY_PROFILE not found'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'ARRAY_PROFILE not found'
Thu May 25 23:08:16 2023 - ERROR - ARRAY_PROFILE not found
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_09.sh line 37'
+ message='oe_test_service_atuned_09.sh line 37'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_09.sh line 37'
Thu May 25 23:08:16 2023 - ERROR - oe_test_service_atuned_09.sh line 37
+ '[' 0 -eq 1 ']'
+ return 0
+ (( i++ ))
+ (( i<46 ))
+ atune-adm profile basic-test-suite-baseline-stream
+ CHECK_RESULT 1 0 0 'atune-adm profile failure'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='atune-adm profile failure'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'atune-adm profile failure'
+ LOG_ERROR 'atune-adm profile failure'
+ message='atune-adm profile failure'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'atune-adm profile failure'
Thu May 25 23:08:17 2023 - ERROR - atune-adm profile failure
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_09.sh line 32'
+ message='oe_test_service_atuned_09.sh line 32'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_09.sh line 32'
Thu May 25 23:08:18 2023 - ERROR - oe_test_service_atuned_09.sh line 32
+ '[' 0 -eq 1 ']'
+ return 0
+ grep -i 'load profile basic-test-suite-baseline-stream Faild' temp.log
+ CHECK_RESULT 1 0 1 'load profile exist'
+ actual_result=1
+ expect_result=0
+ mode=1
+ error_log='load profile exist'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 1 -eq 0 ']'
+ test 1x == 0x
+ return 0
+ atune-adm list
failed to dial "/var/run/atuned/atuned.sock" : connection error: desc = "transport: error while dialing: dial unix /var/run/atuned/atuned.sock: connect: connection refused"
+ grep basic-test-suite-baseline-stream temp.log
+ grep true
+ CHECK_RESULT 1 0 0 'ARRAY_PROFILE not found'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='ARRAY_PROFILE not found'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'ARRAY_PROFILE not found'
+ LOG_ERROR 'ARRAY_PROFILE not found'
+ message='ARRAY_PROFILE not found'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'ARRAY_PROFILE not found'
Thu May 25 23:08:18 2023 - ERROR - ARRAY_PROFILE not found
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_09.sh line 37'
+ message='oe_test_service_atuned_09.sh line 37'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_09.sh line 37'
Thu May 25 23:08:19 2023 - ERROR - oe_test_service_atuned_09.sh line 37
+ '[' 0 -eq 1 ']'
+ return 0
+ (( i++ ))
+ (( i<46 ))
+ atune-adm profile basic-test-suite-baseline-unixbench
+ CHECK_RESULT 1 0 0 'atune-adm profile failure'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='atune-adm profile failure'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'atune-adm profile failure'
+ LOG_ERROR 'atune-adm profile failure'
+ message='atune-adm profile failure'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'atune-adm profile failure'
Thu May 25 23:08:20 2023 - ERROR - atune-adm profile failure
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_09.sh line 32'
+ message='oe_test_service_atuned_09.sh line 32'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_09.sh line 32'
Thu May 25 23:08:20 2023 - ERROR - oe_test_service_atuned_09.sh line 32
+ '[' 0 -eq 1 ']'
+ return 0
+ grep -i 'load profile basic-test-suite-baseline-unixbench Faild' temp.log
+ CHECK_RESULT 1 0 1 'load profile exist'
+ actual_result=1
+ expect_result=0
+ mode=1
+ error_log='load profile exist'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 1 -eq 0 ']'
+ test 1x == 0x
+ return 0
+ atune-adm list
failed to dial "/var/run/atuned/atuned.sock" : connection error: desc = "transport: error while dialing: dial unix /var/run/atuned/atuned.sock: connect: connection refused"
+ grep basic-test-suite-baseline-unixbench temp.log
+ grep true
+ CHECK_RESULT 1 0 0 'ARRAY_PROFILE not found'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='ARRAY_PROFILE not found'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'ARRAY_PROFILE not found'
+ LOG_ERROR 'ARRAY_PROFILE not found'
+ message='ARRAY_PROFILE not found'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'ARRAY_PROFILE not found'
Thu May 25 23:08:21 2023 - ERROR - ARRAY_PROFILE not found
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_09.sh line 37'
+ message='oe_test_service_atuned_09.sh line 37'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_09.sh line 37'
Thu May 25 23:08:22 2023 - ERROR - oe_test_service_atuned_09.sh line 37
+ '[' 0 -eq 1 ']'
+ return 0
+ (( i++ ))
+ (( i<46 ))
+ atune-adm profile basic-test-suite-speccpu-speccpu2006
+ CHECK_RESULT 1 0 0 'atune-adm profile failure'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='atune-adm profile failure'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'atune-adm profile failure'
+ LOG_ERROR 'atune-adm profile failure'
+ message='atune-adm profile failure'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'atune-adm profile failure'
Thu May 25 23:08:23 2023 - ERROR - atune-adm profile failure
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_09.sh line 32'
+ message='oe_test_service_atuned_09.sh line 32'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_09.sh line 32'
Thu May 25 23:08:23 2023 - ERROR - oe_test_service_atuned_09.sh line 32
+ '[' 0 -eq 1 ']'
+ return 0
+ grep -i 'load profile basic-test-suite-speccpu-speccpu2006 Faild' temp.log
+ CHECK_RESULT 1 0 1 'load profile exist'
+ actual_result=1
+ expect_result=0
+ mode=1
+ error_log='load profile exist'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 1 -eq 0 ']'
+ test 1x == 0x
+ return 0
+ atune-adm list
failed to dial "/var/run/atuned/atuned.sock" : connection error: desc = "transport: error while dialing: dial unix /var/run/atuned/atuned.sock: connect: connection refused"
+ grep basic-test-suite-speccpu-speccpu2006 temp.log
+ grep true
+ CHECK_RESULT 1 0 0 'ARRAY_PROFILE not found'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='ARRAY_PROFILE not found'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'ARRAY_PROFILE not found'
+ LOG_ERROR 'ARRAY_PROFILE not found'
+ message='ARRAY_PROFILE not found'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'ARRAY_PROFILE not found'
Thu May 25 23:08:24 2023 - ERROR - ARRAY_PROFILE not found
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_09.sh line 37'
+ message='oe_test_service_atuned_09.sh line 37'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_09.sh line 37'
Thu May 25 23:08:25 2023 - ERROR - oe_test_service_atuned_09.sh line 37
+ '[' 0 -eq 1 ']'
+ return 0
+ (( i++ ))
+ (( i<46 ))
+ atune-adm profile basic-test-suite-specjbb-specjbb2015
+ CHECK_RESULT 1 0 0 'atune-adm profile failure'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='atune-adm profile failure'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'atune-adm profile failure'
+ LOG_ERROR 'atune-adm profile failure'
+ message='atune-adm profile failure'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'atune-adm profile failure'
Thu May 25 23:08:26 2023 - ERROR - atune-adm profile failure
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_09.sh line 32'
+ message='oe_test_service_atuned_09.sh line 32'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_09.sh line 32'
Thu May 25 23:08:26 2023 - ERROR - oe_test_service_atuned_09.sh line 32
+ '[' 0 -eq 1 ']'
+ return 0
+ grep -i 'load profile basic-test-suite-specjbb-specjbb2015 Faild' temp.log
+ CHECK_RESULT 1 0 1 'load profile exist'
+ actual_result=1
+ expect_result=0
+ mode=1
+ error_log='load profile exist'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 1 -eq 0 ']'
+ test 1x == 0x
+ return 0
+ atune-adm list
failed to dial "/var/run/atuned/atuned.sock" : connection error: desc = "transport: error while dialing: dial unix /var/run/atuned/atuned.sock: connect: connection refused"
+ grep basic-test-suite-specjbb-specjbb2015 temp.log
+ grep true
+ CHECK_RESULT 1 0 0 'ARRAY_PROFILE not found'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='ARRAY_PROFILE not found'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'ARRAY_PROFILE not found'
+ LOG_ERROR 'ARRAY_PROFILE not found'
+ message='ARRAY_PROFILE not found'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'ARRAY_PROFILE not found'
Thu May 25 23:08:27 2023 - ERROR - ARRAY_PROFILE not found
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_09.sh line 37'
+ message='oe_test_service_atuned_09.sh line 37'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_09.sh line 37'
Thu May 25 23:08:28 2023 - ERROR - oe_test_service_atuned_09.sh line 37
+ '[' 0 -eq 1 ']'
+ return 0
+ (( i++ ))
+ (( i<46 ))
+ atune-adm profile big-data-hadoop-hdfs-dfsio-hdd
+ CHECK_RESULT 1 0 0 'atune-adm profile failure'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='atune-adm profile failure'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'atune-adm profile failure'
+ LOG_ERROR 'atune-adm profile failure'
+ message='atune-adm profile failure'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'atune-adm profile failure'
Thu May 25 23:08:28 2023 - ERROR - atune-adm profile failure
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_09.sh line 32'
+ message='oe_test_service_atuned_09.sh line 32'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_09.sh line 32'
Thu May 25 23:08:29 2023 - ERROR - oe_test_service_atuned_09.sh line 32
+ '[' 0 -eq 1 ']'
+ return 0
+ grep -i 'load profile big-data-hadoop-hdfs-dfsio-hdd Faild' temp.log
+ CHECK_RESULT 1 0 1 'load profile exist'
+ actual_result=1
+ expect_result=0
+ mode=1
+ error_log='load profile exist'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 1 -eq 0 ']'
+ test 1x == 0x
+ return 0
+ atune-adm list
failed to dial "/var/run/atuned/atuned.sock" : connection error: desc = "transport: error while dialing: dial unix /var/run/atuned/atuned.sock: connect: connection refused"
+ grep big-data-hadoop-hdfs-dfsio-hdd temp.log
+ grep true
+ CHECK_RESULT 1 0 0 'ARRAY_PROFILE not found'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='ARRAY_PROFILE not found'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'ARRAY_PROFILE not found'
+ LOG_ERROR 'ARRAY_PROFILE not found'
+ message='ARRAY_PROFILE not found'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'ARRAY_PROFILE not found'
Thu May 25 23:08:30 2023 - ERROR - ARRAY_PROFILE not found
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_09.sh line 37'
+ message='oe_test_service_atuned_09.sh line 37'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_09.sh line 37'
Thu May 25 23:08:30 2023 - ERROR - oe_test_service_atuned_09.sh line 37
+ '[' 0 -eq 1 ']'
+ return 0
+ (( i++ ))
+ (( i<46 ))
+ atune-adm profile big-data-hadoop-hdfs-dfsio-ssd
+ CHECK_RESULT 1 0 0 'atune-adm profile failure'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='atune-adm profile failure'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'atune-adm profile failure'
+ LOG_ERROR 'atune-adm profile failure'
+ message='atune-adm profile failure'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'atune-adm profile failure'
Thu May 25 23:08:31 2023 - ERROR - atune-adm profile failure
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_09.sh line 32'
+ message='oe_test_service_atuned_09.sh line 32'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_09.sh line 32'
Thu May 25 23:08:31 2023 - ERROR - oe_test_service_atuned_09.sh line 32
+ '[' 0 -eq 1 ']'
+ return 0
+ grep -i 'load profile big-data-hadoop-hdfs-dfsio-ssd Faild' temp.log
+ CHECK_RESULT 1 0 1 'load profile exist'
+ actual_result=1
+ expect_result=0
+ mode=1
+ error_log='load profile exist'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 1 -eq 0 ']'
+ test 1x == 0x
+ return 0
+ atune-adm list
failed to dial "/var/run/atuned/atuned.sock" : connection error: desc = "transport: error while dialing: dial unix /var/run/atuned/atuned.sock: connect: connection refused"
+ grep big-data-hadoop-hdfs-dfsio-ssd temp.log
+ grep true
+ CHECK_RESULT 1 0 0 'ARRAY_PROFILE not found'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='ARRAY_PROFILE not found'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'ARRAY_PROFILE not found'
+ LOG_ERROR 'ARRAY_PROFILE not found'
+ message='ARRAY_PROFILE not found'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'ARRAY_PROFILE not found'
Thu May 25 23:08:32 2023 - ERROR - ARRAY_PROFILE not found
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_09.sh line 37'
+ message='oe_test_service_atuned_09.sh line 37'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_09.sh line 37'
Thu May 25 23:08:33 2023 - ERROR - oe_test_service_atuned_09.sh line 37
+ '[' 0 -eq 1 ']'
+ return 0
+ (( i++ ))
+ (( i<46 ))
+ atune-adm profile big-data-hadoop-spark-bayesian
+ CHECK_RESULT 1 0 0 'atune-adm profile failure'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='atune-adm profile failure'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'atune-adm profile failure'
+ LOG_ERROR 'atune-adm profile failure'
+ message='atune-adm profile failure'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'atune-adm profile failure'
Thu May 25 23:08:34 2023 - ERROR - atune-adm profile failure
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_09.sh line 32'
+ message='oe_test_service_atuned_09.sh line 32'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_09.sh line 32'
Thu May 25 23:08:34 2023 - ERROR - oe_test_service_atuned_09.sh line 32
+ '[' 0 -eq 1 ']'
+ return 0
+ grep -i 'load profile big-data-hadoop-spark-bayesian Faild' temp.log
+ CHECK_RESULT 1 0 1 'load profile exist'
+ actual_result=1
+ expect_result=0
+ mode=1
+ error_log='load profile exist'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 1 -eq 0 ']'
+ test 1x == 0x
+ return 0
+ atune-adm list
failed to dial "/var/run/atuned/atuned.sock" : connection error: desc = "transport: error while dialing: dial unix /var/run/atuned/atuned.sock: connect: connection refused"
+ grep big-data-hadoop-spark-bayesian temp.log
+ grep true
+ CHECK_RESULT 1 0 0 'ARRAY_PROFILE not found'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='ARRAY_PROFILE not found'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'ARRAY_PROFILE not found'
+ LOG_ERROR 'ARRAY_PROFILE not found'
+ message='ARRAY_PROFILE not found'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'ARRAY_PROFILE not found'
Thu May 25 23:08:35 2023 - ERROR - ARRAY_PROFILE not found
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_09.sh line 37'
+ message='oe_test_service_atuned_09.sh line 37'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_09.sh line 37'
Thu May 25 23:08:35 2023 - ERROR - oe_test_service_atuned_09.sh line 37
+ '[' 0 -eq 1 ']'
+ return 0
+ (( i++ ))
+ (( i<46 ))
+ atune-adm profile big-data-hadoop-spark-kmeans
+ CHECK_RESULT 1 0 0 'atune-adm profile failure'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='atune-adm profile failure'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'atune-adm profile failure'
+ LOG_ERROR 'atune-adm profile failure'
+ message='atune-adm profile failure'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'atune-adm profile failure'
Thu May 25 23:08:36 2023 - ERROR - atune-adm profile failure
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_09.sh line 32'
+ message='oe_test_service_atuned_09.sh line 32'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_09.sh line 32'
Thu May 25 23:08:37 2023 - ERROR - oe_test_service_atuned_09.sh line 32
+ '[' 0 -eq 1 ']'
+ return 0
+ grep -i 'load profile big-data-hadoop-spark-kmeans Faild' temp.log
+ CHECK_RESULT 1 0 1 'load profile exist'
+ actual_result=1
+ expect_result=0
+ mode=1
+ error_log='load profile exist'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 1 -eq 0 ']'
+ test 1x == 0x
+ return 0
+ atune-adm list
failed to dial "/var/run/atuned/atuned.sock" : connection error: desc = "transport: error while dialing: dial unix /var/run/atuned/atuned.sock: connect: connection refused"
+ grep big-data-hadoop-spark-kmeans temp.log
+ grep true
+ CHECK_RESULT 1 0 0 'ARRAY_PROFILE not found'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='ARRAY_PROFILE not found'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'ARRAY_PROFILE not found'
+ LOG_ERROR 'ARRAY_PROFILE not found'
+ message='ARRAY_PROFILE not found'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'ARRAY_PROFILE not found'
Thu May 25 23:08:38 2023 - ERROR - ARRAY_PROFILE not found
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_09.sh line 37'
+ message='oe_test_service_atuned_09.sh line 37'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_09.sh line 37'
Thu May 25 23:08:38 2023 - ERROR - oe_test_service_atuned_09.sh line 37
+ '[' 0 -eq 1 ']'
+ return 0
+ (( i++ ))
+ (( i<46 ))
+ atune-adm profile big-data-hadoop-spark-sql1
+ CHECK_RESULT 1 0 0 'atune-adm profile failure'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='atune-adm profile failure'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'atune-adm profile failure'
+ LOG_ERROR 'atune-adm profile failure'
+ message='atune-adm profile failure'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'atune-adm profile failure'
Thu May 25 23:08:39 2023 - ERROR - atune-adm profile failure
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_09.sh line 32'
+ message='oe_test_service_atuned_09.sh line 32'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_09.sh line 32'
Thu May 25 23:08:40 2023 - ERROR - oe_test_service_atuned_09.sh line 32
+ '[' 0 -eq 1 ']'
+ return 0
+ grep -i 'load profile big-data-hadoop-spark-sql1 Faild' temp.log
+ CHECK_RESULT 1 0 1 'load profile exist'
+ actual_result=1
+ expect_result=0
+ mode=1
+ error_log='load profile exist'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 1 -eq 0 ']'
+ test 1x == 0x
+ return 0
+ atune-adm list
failed to dial "/var/run/atuned/atuned.sock" : connection error: desc = "transport: error while dialing: dial unix /var/run/atuned/atuned.sock: connect: connection refused"
+ grep big-data-hadoop-spark-sql1 temp.log
+ grep true
+ CHECK_RESULT 1 0 0 'ARRAY_PROFILE not found'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='ARRAY_PROFILE not found'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'ARRAY_PROFILE not found'
+ LOG_ERROR 'ARRAY_PROFILE not found'
+ message='ARRAY_PROFILE not found'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'ARRAY_PROFILE not found'
Thu May 25 23:08:40 2023 - ERROR - ARRAY_PROFILE not found
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_09.sh line 37'
+ message='oe_test_service_atuned_09.sh line 37'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_09.sh line 37'
Thu May 25 23:08:41 2023 - ERROR - oe_test_service_atuned_09.sh line 37
+ '[' 0 -eq 1 ']'
+ return 0
+ (( i++ ))
+ (( i<46 ))
+ atune-adm profile big-data-hadoop-spark-sql10
+ CHECK_RESULT 1 0 0 'atune-adm profile failure'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='atune-adm profile failure'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'atune-adm profile failure'
+ LOG_ERROR 'atune-adm profile failure'
+ message='atune-adm profile failure'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'atune-adm profile failure'
Thu May 25 23:08:42 2023 - ERROR - atune-adm profile failure
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_09.sh line 32'
+ message='oe_test_service_atuned_09.sh line 32'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_09.sh line 32'
Thu May 25 23:08:42 2023 - ERROR - oe_test_service_atuned_09.sh line 32
+ '[' 0 -eq 1 ']'
+ return 0
+ grep -i 'load profile big-data-hadoop-spark-sql10 Faild' temp.log
+ CHECK_RESULT 1 0 1 'load profile exist'
+ actual_result=1
+ expect_result=0
+ mode=1
+ error_log='load profile exist'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 1 -eq 0 ']'
+ test 1x == 0x
+ return 0
+ atune-adm list
failed to dial "/var/run/atuned/atuned.sock" : connection error: desc = "transport: error while dialing: dial unix /var/run/atuned/atuned.sock: connect: connection refused"
+ grep big-data-hadoop-spark-sql10 temp.log
+ grep true
+ CHECK_RESULT 1 0 0 'ARRAY_PROFILE not found'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='ARRAY_PROFILE not found'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'ARRAY_PROFILE not found'
+ LOG_ERROR 'ARRAY_PROFILE not found'
+ message='ARRAY_PROFILE not found'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'ARRAY_PROFILE not found'
Thu May 25 23:08:43 2023 - ERROR - ARRAY_PROFILE not found
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_09.sh line 37'
+ message='oe_test_service_atuned_09.sh line 37'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_09.sh line 37'
Thu May 25 23:08:44 2023 - ERROR - oe_test_service_atuned_09.sh line 37
+ '[' 0 -eq 1 ']'
+ return 0
+ (( i++ ))
+ (( i<46 ))
+ atune-adm profile big-data-hadoop-spark-sql2
+ CHECK_RESULT 1 0 0 'atune-adm profile failure'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='atune-adm profile failure'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'atune-adm profile failure'
+ LOG_ERROR 'atune-adm profile failure'
+ message='atune-adm profile failure'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'atune-adm profile failure'
Thu May 25 23:08:45 2023 - ERROR - atune-adm profile failure
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_09.sh line 32'
+ message='oe_test_service_atuned_09.sh line 32'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_09.sh line 32'
Thu May 25 23:08:45 2023 - ERROR - oe_test_service_atuned_09.sh line 32
+ '[' 0 -eq 1 ']'
+ return 0
+ grep -i 'load profile big-data-hadoop-spark-sql2 Faild' temp.log
+ CHECK_RESULT 1 0 1 'load profile exist'
+ actual_result=1
+ expect_result=0
+ mode=1
+ error_log='load profile exist'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 1 -eq 0 ']'
+ test 1x == 0x
+ return 0
+ atune-adm list
failed to dial "/var/run/atuned/atuned.sock" : connection error: desc = "transport: error while dialing: dial unix /var/run/atuned/atuned.sock: connect: connection refused"
+ grep big-data-hadoop-spark-sql2 temp.log
+ grep true
+ CHECK_RESULT 1 0 0 'ARRAY_PROFILE not found'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='ARRAY_PROFILE not found'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'ARRAY_PROFILE not found'
+ LOG_ERROR 'ARRAY_PROFILE not found'
+ message='ARRAY_PROFILE not found'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'ARRAY_PROFILE not found'
Thu May 25 23:08:46 2023 - ERROR - ARRAY_PROFILE not found
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_09.sh line 37'
+ message='oe_test_service_atuned_09.sh line 37'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_09.sh line 37'
Thu May 25 23:08:47 2023 - ERROR - oe_test_service_atuned_09.sh line 37
+ '[' 0 -eq 1 ']'
+ return 0
+ (( i++ ))
+ (( i<46 ))
+ atune-adm profile big-data-hadoop-spark-sql3
+ CHECK_RESULT 1 0 0 'atune-adm profile failure'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='atune-adm profile failure'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'atune-adm profile failure'
+ LOG_ERROR 'atune-adm profile failure'
+ message='atune-adm profile failure'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'atune-adm profile failure'
Thu May 25 23:08:47 2023 - ERROR - atune-adm profile failure
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_09.sh line 32'
+ message='oe_test_service_atuned_09.sh line 32'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_09.sh line 32'
Thu May 25 23:08:48 2023 - ERROR - oe_test_service_atuned_09.sh line 32
+ '[' 0 -eq 1 ']'
+ return 0
+ grep -i 'load profile big-data-hadoop-spark-sql3 Faild' temp.log
+ CHECK_RESULT 1 0 1 'load profile exist'
+ actual_result=1
+ expect_result=0
+ mode=1
+ error_log='load profile exist'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 1 -eq 0 ']'
+ test 1x == 0x
+ return 0
+ atune-adm list
failed to dial "/var/run/atuned/atuned.sock" : connection error: desc = "transport: error while dialing: dial unix /var/run/atuned/atuned.sock: connect: connection refused"
+ grep big-data-hadoop-spark-sql3 temp.log
+ grep true
+ CHECK_RESULT 1 0 0 'ARRAY_PROFILE not found'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='ARRAY_PROFILE not found'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'ARRAY_PROFILE not found'
+ LOG_ERROR 'ARRAY_PROFILE not found'
+ message='ARRAY_PROFILE not found'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'ARRAY_PROFILE not found'
Thu May 25 23:08:49 2023 - ERROR - ARRAY_PROFILE not found
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_09.sh line 37'
+ message='oe_test_service_atuned_09.sh line 37'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_09.sh line 37'
Thu May 25 23:08:49 2023 - ERROR - oe_test_service_atuned_09.sh line 37
+ '[' 0 -eq 1 ']'
+ return 0
+ (( i++ ))
+ (( i<46 ))
+ atune-adm profile big-data-hadoop-spark-sql4
+ CHECK_RESULT 1 0 0 'atune-adm profile failure'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='atune-adm profile failure'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'atune-adm profile failure'
+ LOG_ERROR 'atune-adm profile failure'
+ message='atune-adm profile failure'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'atune-adm profile failure'
Thu May 25 23:08:50 2023 - ERROR - atune-adm profile failure
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_09.sh line 32'
+ message='oe_test_service_atuned_09.sh line 32'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_09.sh line 32'
Thu May 25 23:08:51 2023 - ERROR - oe_test_service_atuned_09.sh line 32
+ '[' 0 -eq 1 ']'
+ return 0
+ grep -i 'load profile big-data-hadoop-spark-sql4 Faild' temp.log
+ CHECK_RESULT 1 0 1 'load profile exist'
+ actual_result=1
+ expect_result=0
+ mode=1
+ error_log='load profile exist'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 1 -eq 0 ']'
+ test 1x == 0x
+ return 0
+ atune-adm list
failed to dial "/var/run/atuned/atuned.sock" : connection error: desc = "transport: error while dialing: dial unix /var/run/atuned/atuned.sock: connect: connection refused"
+ grep big-data-hadoop-spark-sql4 temp.log
+ grep true
+ CHECK_RESULT 1 0 0 'ARRAY_PROFILE not found'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='ARRAY_PROFILE not found'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'ARRAY_PROFILE not found'
+ LOG_ERROR 'ARRAY_PROFILE not found'
+ message='ARRAY_PROFILE not found'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'ARRAY_PROFILE not found'
Thu May 25 23:08:52 2023 - ERROR - ARRAY_PROFILE not found
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_09.sh line 37'
+ message='oe_test_service_atuned_09.sh line 37'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_09.sh line 37'
Thu May 25 23:08:52 2023 - ERROR - oe_test_service_atuned_09.sh line 37
+ '[' 0 -eq 1 ']'
+ return 0
+ (( i++ ))
+ (( i<46 ))
+ atune-adm profile big-data-hadoop-spark-sql5
+ CHECK_RESULT 1 0 0 'atune-adm profile failure'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='atune-adm profile failure'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'atune-adm profile failure'
+ LOG_ERROR 'atune-adm profile failure'
+ message='atune-adm profile failure'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'atune-adm profile failure'
Thu May 25 23:08:53 2023 - ERROR - atune-adm profile failure
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_09.sh line 32'
+ message='oe_test_service_atuned_09.sh line 32'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_09.sh line 32'
Thu May 25 23:08:53 2023 - ERROR - oe_test_service_atuned_09.sh line 32
+ '[' 0 -eq 1 ']'
+ return 0
+ grep -i 'load profile big-data-hadoop-spark-sql5 Faild' temp.log
+ CHECK_RESULT 1 0 1 'load profile exist'
+ actual_result=1
+ expect_result=0
+ mode=1
+ error_log='load profile exist'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 1 -eq 0 ']'
+ test 1x == 0x
+ return 0
+ atune-adm list
failed to dial "/var/run/atuned/atuned.sock" : connection error: desc = "transport: error while dialing: dial unix /var/run/atuned/atuned.sock: connect: connection refused"
+ grep big-data-hadoop-spark-sql5 temp.log
+ grep true
+ CHECK_RESULT 1 0 0 'ARRAY_PROFILE not found'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='ARRAY_PROFILE not found'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'ARRAY_PROFILE not found'
+ LOG_ERROR 'ARRAY_PROFILE not found'
+ message='ARRAY_PROFILE not found'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'ARRAY_PROFILE not found'
Thu May 25 23:08:54 2023 - ERROR - ARRAY_PROFILE not found
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_09.sh line 37'
+ message='oe_test_service_atuned_09.sh line 37'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_09.sh line 37'
Thu May 25 23:08:55 2023 - ERROR - oe_test_service_atuned_09.sh line 37
+ '[' 0 -eq 1 ']'
+ return 0
+ (( i++ ))
+ (( i<46 ))
+ atune-adm profile big-data-hadoop-spark-sql6
+ CHECK_RESULT 1 0 0 'atune-adm profile failure'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='atune-adm profile failure'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'atune-adm profile failure'
+ LOG_ERROR 'atune-adm profile failure'
+ message='atune-adm profile failure'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'atune-adm profile failure'
Thu May 25 23:08:56 2023 - ERROR - atune-adm profile failure
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_09.sh line 32'
+ message='oe_test_service_atuned_09.sh line 32'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_09.sh line 32'
Thu May 25 23:08:56 2023 - ERROR - oe_test_service_atuned_09.sh line 32
+ '[' 0 -eq 1 ']'
+ return 0
+ grep -i 'load profile big-data-hadoop-spark-sql6 Faild' temp.log
+ CHECK_RESULT 1 0 1 'load profile exist'
+ actual_result=1
+ expect_result=0
+ mode=1
+ error_log='load profile exist'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 1 -eq 0 ']'
+ test 1x == 0x
+ return 0
+ atune-adm list
failed to dial "/var/run/atuned/atuned.sock" : connection error: desc = "transport: error while dialing: dial unix /var/run/atuned/atuned.sock: connect: connection refused"
+ grep big-data-hadoop-spark-sql6 temp.log
+ grep true
+ CHECK_RESULT 1 0 0 'ARRAY_PROFILE not found'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='ARRAY_PROFILE not found'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'ARRAY_PROFILE not found'
+ LOG_ERROR 'ARRAY_PROFILE not found'
+ message='ARRAY_PROFILE not found'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'ARRAY_PROFILE not found'
Thu May 25 23:08:57 2023 - ERROR - ARRAY_PROFILE not found
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_09.sh line 37'
+ message='oe_test_service_atuned_09.sh line 37'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_09.sh line 37'
Thu May 25 23:08:58 2023 - ERROR - oe_test_service_atuned_09.sh line 37
+ '[' 0 -eq 1 ']'
+ return 0
+ (( i++ ))
+ (( i<46 ))
+ atune-adm profile big-data-hadoop-spark-sql7
+ CHECK_RESULT 1 0 0 'atune-adm profile failure'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='atune-adm profile failure'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'atune-adm profile failure'
+ LOG_ERROR 'atune-adm profile failure'
+ message='atune-adm profile failure'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'atune-adm profile failure'
Thu May 25 23:08:58 2023 - ERROR - atune-adm profile failure
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_09.sh line 32'
+ message='oe_test_service_atuned_09.sh line 32'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_09.sh line 32'
Thu May 25 23:08:59 2023 - ERROR - oe_test_service_atuned_09.sh line 32
+ '[' 0 -eq 1 ']'
+ return 0
+ grep -i 'load profile big-data-hadoop-spark-sql7 Faild' temp.log
+ CHECK_RESULT 1 0 1 'load profile exist'
+ actual_result=1
+ expect_result=0
+ mode=1
+ error_log='load profile exist'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 1 -eq 0 ']'
+ test 1x == 0x
+ return 0
+ atune-adm list
failed to dial "/var/run/atuned/atuned.sock" : connection error: desc = "transport: error while dialing: dial unix /var/run/atuned/atuned.sock: connect: connection refused"
+ grep big-data-hadoop-spark-sql7 temp.log
+ grep true
+ CHECK_RESULT 1 0 0 'ARRAY_PROFILE not found'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='ARRAY_PROFILE not found'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'ARRAY_PROFILE not found'
+ LOG_ERROR 'ARRAY_PROFILE not found'
+ message='ARRAY_PROFILE not found'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'ARRAY_PROFILE not found'
Thu May 25 23:09:00 2023 - ERROR - ARRAY_PROFILE not found
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_09.sh line 37'
+ message='oe_test_service_atuned_09.sh line 37'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_09.sh line 37'
Thu May 25 23:09:00 2023 - ERROR - oe_test_service_atuned_09.sh line 37
+ '[' 0 -eq 1 ']'
+ return 0
+ (( i++ ))
+ (( i<46 ))
+ atune-adm profile big-data-hadoop-spark-sql8
+ CHECK_RESULT 1 0 0 'atune-adm profile failure'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='atune-adm profile failure'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'atune-adm profile failure'
+ LOG_ERROR 'atune-adm profile failure'
+ message='atune-adm profile failure'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'atune-adm profile failure'
Thu May 25 23:09:01 2023 - ERROR - atune-adm profile failure
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_09.sh line 32'
+ message='oe_test_service_atuned_09.sh line 32'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_09.sh line 32'
Thu May 25 23:09:02 2023 - ERROR - oe_test_service_atuned_09.sh line 32
+ '[' 0 -eq 1 ']'
+ return 0
+ grep -i 'load profile big-data-hadoop-spark-sql8 Faild' temp.log
+ CHECK_RESULT 1 0 1 'load profile exist'
+ actual_result=1
+ expect_result=0
+ mode=1
+ error_log='load profile exist'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 1 -eq 0 ']'
+ test 1x == 0x
+ return 0
+ atune-adm list
failed to dial "/var/run/atuned/atuned.sock" : connection error: desc = "transport: error while dialing: dial unix /var/run/atuned/atuned.sock: connect: connection refused"
+ grep big-data-hadoop-spark-sql8 temp.log
+ grep true
+ CHECK_RESULT 1 0 0 'ARRAY_PROFILE not found'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='ARRAY_PROFILE not found'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'ARRAY_PROFILE not found'
+ LOG_ERROR 'ARRAY_PROFILE not found'
+ message='ARRAY_PROFILE not found'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'ARRAY_PROFILE not found'
Thu May 25 23:09:03 2023 - ERROR - ARRAY_PROFILE not found
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_09.sh line 37'
+ message='oe_test_service_atuned_09.sh line 37'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_09.sh line 37'
Thu May 25 23:09:03 2023 - ERROR - oe_test_service_atuned_09.sh line 37
+ '[' 0 -eq 1 ']'
+ return 0
+ (( i++ ))
+ (( i<46 ))
+ atune-adm profile big-data-hadoop-spark-sql9
+ CHECK_RESULT 1 0 0 'atune-adm profile failure'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='atune-adm profile failure'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'atune-adm profile failure'
+ LOG_ERROR 'atune-adm profile failure'
+ message='atune-adm profile failure'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'atune-adm profile failure'
Thu May 25 23:09:04 2023 - ERROR - atune-adm profile failure
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_09.sh line 32'
+ message='oe_test_service_atuned_09.sh line 32'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_09.sh line 32'
Thu May 25 23:09:04 2023 - ERROR - oe_test_service_atuned_09.sh line 32
+ '[' 0 -eq 1 ']'
+ return 0
+ grep -i 'load profile big-data-hadoop-spark-sql9 Faild' temp.log
+ CHECK_RESULT 1 0 1 'load profile exist'
+ actual_result=1
+ expect_result=0
+ mode=1
+ error_log='load profile exist'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 1 -eq 0 ']'
+ test 1x == 0x
+ return 0
+ atune-adm list
failed to dial "/var/run/atuned/atuned.sock" : connection error: desc = "transport: error while dialing: dial unix /var/run/atuned/atuned.sock: connect: connection refused"
+ grep big-data-hadoop-spark-sql9 temp.log
+ grep true
+ CHECK_RESULT 1 0 0 'ARRAY_PROFILE not found'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='ARRAY_PROFILE not found'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'ARRAY_PROFILE not found'
+ LOG_ERROR 'ARRAY_PROFILE not found'
+ message='ARRAY_PROFILE not found'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'ARRAY_PROFILE not found'
Thu May 25 23:09:05 2023 - ERROR - ARRAY_PROFILE not found
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_09.sh line 37'
+ message='oe_test_service_atuned_09.sh line 37'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_09.sh line 37'
Thu May 25 23:09:06 2023 - ERROR - oe_test_service_atuned_09.sh line 37
+ '[' 0 -eq 1 ']'
+ return 0
+ (( i++ ))
+ (( i<46 ))
+ atune-adm profile big-data-hadoop-spark-tersort
+ CHECK_RESULT 1 0 0 'atune-adm profile failure'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='atune-adm profile failure'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'atune-adm profile failure'
+ LOG_ERROR 'atune-adm profile failure'
+ message='atune-adm profile failure'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'atune-adm profile failure'
Thu May 25 23:09:07 2023 - ERROR - atune-adm profile failure
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_09.sh line 32'
+ message='oe_test_service_atuned_09.sh line 32'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_09.sh line 32'
Thu May 25 23:09:07 2023 - ERROR - oe_test_service_atuned_09.sh line 32
+ '[' 0 -eq 1 ']'
+ return 0
+ grep -i 'load profile big-data-hadoop-spark-tersort Faild' temp.log
+ CHECK_RESULT 1 0 1 'load profile exist'
+ actual_result=1
+ expect_result=0
+ mode=1
+ error_log='load profile exist'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 1 -eq 0 ']'
+ test 1x == 0x
+ return 0
+ atune-adm list
failed to dial "/var/run/atuned/atuned.sock" : connection error: desc = "transport: error while dialing: dial unix /var/run/atuned/atuned.sock: connect: connection refused"
+ grep big-data-hadoop-spark-tersort temp.log
+ grep true
+ CHECK_RESULT 1 0 0 'ARRAY_PROFILE not found'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='ARRAY_PROFILE not found'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'ARRAY_PROFILE not found'
+ LOG_ERROR 'ARRAY_PROFILE not found'
+ message='ARRAY_PROFILE not found'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'ARRAY_PROFILE not found'
Thu May 25 23:09:08 2023 - ERROR - ARRAY_PROFILE not found
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_09.sh line 37'
+ message='oe_test_service_atuned_09.sh line 37'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_09.sh line 37'
Thu May 25 23:09:09 2023 - ERROR - oe_test_service_atuned_09.sh line 37
+ '[' 0 -eq 1 ']'
+ return 0
+ (( i++ ))
+ (( i<46 ))
+ atune-adm profile big-data-hadoop-spark-wordcount
+ CHECK_RESULT 1 0 0 'atune-adm profile failure'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='atune-adm profile failure'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'atune-adm profile failure'
+ LOG_ERROR 'atune-adm profile failure'
+ message='atune-adm profile failure'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'atune-adm profile failure'
Thu May 25 23:09:10 2023 - ERROR - atune-adm profile failure
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_09.sh line 32'
+ message='oe_test_service_atuned_09.sh line 32'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_09.sh line 32'
Thu May 25 23:09:10 2023 - ERROR - oe_test_service_atuned_09.sh line 32
+ '[' 0 -eq 1 ']'
+ return 0
+ grep -i 'load profile big-data-hadoop-spark-wordcount Faild' temp.log
+ CHECK_RESULT 1 0 1 'load profile exist'
+ actual_result=1
+ expect_result=0
+ mode=1
+ error_log='load profile exist'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 1 -eq 0 ']'
+ test 1x == 0x
+ return 0
+ atune-adm list
failed to dial "/var/run/atuned/atuned.sock" : connection error: desc = "transport: error while dialing: dial unix /var/run/atuned/atuned.sock: connect: connection refused"
+ grep big-data-hadoop-spark-wordcount temp.log
+ grep true
+ CHECK_RESULT 1 0 0 'ARRAY_PROFILE not found'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='ARRAY_PROFILE not found'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'ARRAY_PROFILE not found'
+ LOG_ERROR 'ARRAY_PROFILE not found'
+ message='ARRAY_PROFILE not found'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'ARRAY_PROFILE not found'
Thu May 25 23:09:11 2023 - ERROR - ARRAY_PROFILE not found
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_09.sh line 37'
+ message='oe_test_service_atuned_09.sh line 37'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_09.sh line 37'
Thu May 25 23:09:12 2023 - ERROR - oe_test_service_atuned_09.sh line 37
+ '[' 0 -eq 1 ']'
+ return 0
+ (( i++ ))
+ (( i<46 ))
+ atune-adm profile cloud-compute-kvm-host
+ CHECK_RESULT 1 0 0 'atune-adm profile failure'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='atune-adm profile failure'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'atune-adm profile failure'
+ LOG_ERROR 'atune-adm profile failure'
+ message='atune-adm profile failure'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'atune-adm profile failure'
Thu May 25 23:09:12 2023 - ERROR - atune-adm profile failure
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_09.sh line 32'
+ message='oe_test_service_atuned_09.sh line 32'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_09.sh line 32'
Thu May 25 23:09:13 2023 - ERROR - oe_test_service_atuned_09.sh line 32
+ '[' 0 -eq 1 ']'
+ return 0
+ grep -i 'load profile cloud-compute-kvm-host Faild' temp.log
+ CHECK_RESULT 1 0 1 'load profile exist'
+ actual_result=1
+ expect_result=0
+ mode=1
+ error_log='load profile exist'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 1 -eq 0 ']'
+ test 1x == 0x
+ return 0
+ atune-adm list
failed to dial "/var/run/atuned/atuned.sock" : connection error: desc = "transport: error while dialing: dial unix /var/run/atuned/atuned.sock: connect: connection refused"
+ grep cloud-compute-kvm-host temp.log
+ grep true
+ CHECK_RESULT 1 0 0 'ARRAY_PROFILE not found'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='ARRAY_PROFILE not found'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'ARRAY_PROFILE not found'
+ LOG_ERROR 'ARRAY_PROFILE not found'
+ message='ARRAY_PROFILE not found'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'ARRAY_PROFILE not found'
Thu May 25 23:09:14 2023 - ERROR - ARRAY_PROFILE not found
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_09.sh line 37'
+ message='oe_test_service_atuned_09.sh line 37'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_09.sh line 37'
Thu May 25 23:09:14 2023 - ERROR - oe_test_service_atuned_09.sh line 37
+ '[' 0 -eq 1 ']'
+ return 0
+ (( i++ ))
+ (( i<46 ))
+ atune-adm profile database-mariadb-2p-tpcc-c3
+ CHECK_RESULT 1 0 0 'atune-adm profile failure'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='atune-adm profile failure'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'atune-adm profile failure'
+ LOG_ERROR 'atune-adm profile failure'
+ message='atune-adm profile failure'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'atune-adm profile failure'
Thu May 25 23:09:15 2023 - ERROR - atune-adm profile failure
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_09.sh line 32'
+ message='oe_test_service_atuned_09.sh line 32'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_09.sh line 32'
Thu May 25 23:09:15 2023 - ERROR - oe_test_service_atuned_09.sh line 32
+ '[' 0 -eq 1 ']'
+ return 0
+ grep -i 'load profile database-mariadb-2p-tpcc-c3 Faild' temp.log
+ CHECK_RESULT 1 0 1 'load profile exist'
+ actual_result=1
+ expect_result=0
+ mode=1
+ error_log='load profile exist'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 1 -eq 0 ']'
+ test 1x == 0x
+ return 0
+ atune-adm list
failed to dial "/var/run/atuned/atuned.sock" : connection error: desc = "transport: error while dialing: dial unix /var/run/atuned/atuned.sock: connect: connection refused"
+ grep database-mariadb-2p-tpcc-c3 temp.log
+ grep true
+ CHECK_RESULT 1 0 0 'ARRAY_PROFILE not found'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='ARRAY_PROFILE not found'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'ARRAY_PROFILE not found'
+ LOG_ERROR 'ARRAY_PROFILE not found'
+ message='ARRAY_PROFILE not found'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'ARRAY_PROFILE not found'
Thu May 25 23:09:16 2023 - ERROR - ARRAY_PROFILE not found
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_09.sh line 37'
+ message='oe_test_service_atuned_09.sh line 37'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_09.sh line 37'
Thu May 25 23:09:17 2023 - ERROR - oe_test_service_atuned_09.sh line 37
+ '[' 0 -eq 1 ']'
+ return 0
+ (( i++ ))
+ (( i<46 ))
+ atune-adm profile database-mariadb-4p-tpcc-c3
+ CHECK_RESULT 1 0 0 'atune-adm profile failure'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='atune-adm profile failure'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'atune-adm profile failure'
+ LOG_ERROR 'atune-adm profile failure'
+ message='atune-adm profile failure'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'atune-adm profile failure'
Thu May 25 23:09:18 2023 - ERROR - atune-adm profile failure
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_09.sh line 32'
+ message='oe_test_service_atuned_09.sh line 32'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_09.sh line 32'
Thu May 25 23:09:18 2023 - ERROR - oe_test_service_atuned_09.sh line 32
+ '[' 0 -eq 1 ']'
+ return 0
+ grep -i 'load profile database-mariadb-4p-tpcc-c3 Faild' temp.log
+ CHECK_RESULT 1 0 1 'load profile exist'
+ actual_result=1
+ expect_result=0
+ mode=1
+ error_log='load profile exist'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 1 -eq 0 ']'
+ test 1x == 0x
+ return 0
+ atune-adm list
failed to dial "/var/run/atuned/atuned.sock" : connection error: desc = "transport: error while dialing: dial unix /var/run/atuned/atuned.sock: connect: connection refused"
+ grep database-mariadb-4p-tpcc-c3 temp.log
+ grep true
+ CHECK_RESULT 1 0 0 'ARRAY_PROFILE not found'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='ARRAY_PROFILE not found'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'ARRAY_PROFILE not found'
+ LOG_ERROR 'ARRAY_PROFILE not found'
+ message='ARRAY_PROFILE not found'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'ARRAY_PROFILE not found'
Thu May 25 23:09:19 2023 - ERROR - ARRAY_PROFILE not found
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_09.sh line 37'
+ message='oe_test_service_atuned_09.sh line 37'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_09.sh line 37'
Thu May 25 23:09:20 2023 - ERROR - oe_test_service_atuned_09.sh line 37
+ '[' 0 -eq 1 ']'
+ return 0
+ (( i++ ))
+ (( i<46 ))
+ atune-adm profile database-mongodb-2p-sysbench
+ CHECK_RESULT 1 0 0 'atune-adm profile failure'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='atune-adm profile failure'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'atune-adm profile failure'
+ LOG_ERROR 'atune-adm profile failure'
+ message='atune-adm profile failure'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'atune-adm profile failure'
Thu May 25 23:09:20 2023 - ERROR - atune-adm profile failure
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_09.sh line 32'
+ message='oe_test_service_atuned_09.sh line 32'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_09.sh line 32'
Thu May 25 23:09:21 2023 - ERROR - oe_test_service_atuned_09.sh line 32
+ '[' 0 -eq 1 ']'
+ return 0
+ grep -i 'load profile database-mongodb-2p-sysbench Faild' temp.log
+ CHECK_RESULT 1 0 1 'load profile exist'
+ actual_result=1
+ expect_result=0
+ mode=1
+ error_log='load profile exist'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 1 -eq 0 ']'
+ test 1x == 0x
+ return 0
+ atune-adm list
failed to dial "/var/run/atuned/atuned.sock" : connection error: desc = "transport: error while dialing: dial unix /var/run/atuned/atuned.sock: connect: connection refused"
+ grep database-mongodb-2p-sysbench temp.log
+ grep true
+ CHECK_RESULT 1 0 0 'ARRAY_PROFILE not found'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='ARRAY_PROFILE not found'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'ARRAY_PROFILE not found'
+ LOG_ERROR 'ARRAY_PROFILE not found'
+ message='ARRAY_PROFILE not found'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'ARRAY_PROFILE not found'
Thu May 25 23:09:22 2023 - ERROR - ARRAY_PROFILE not found
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_09.sh line 37'
+ message='oe_test_service_atuned_09.sh line 37'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_09.sh line 37'
Thu May 25 23:09:22 2023 - ERROR - oe_test_service_atuned_09.sh line 37
+ '[' 0 -eq 1 ']'
+ return 0
+ (( i++ ))
+ (( i<46 ))
+ atune-adm profile database-mysql-2p-sysbench-hdd
+ CHECK_RESULT 1 0 0 'atune-adm profile failure'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='atune-adm profile failure'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'atune-adm profile failure'
+ LOG_ERROR 'atune-adm profile failure'
+ message='atune-adm profile failure'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'atune-adm profile failure'
Thu May 25 23:09:23 2023 - ERROR - atune-adm profile failure
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_09.sh line 32'
+ message='oe_test_service_atuned_09.sh line 32'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_09.sh line 32'
Thu May 25 23:09:23 2023 - ERROR - oe_test_service_atuned_09.sh line 32
+ '[' 0 -eq 1 ']'
+ return 0
+ grep -i 'load profile database-mysql-2p-sysbench-hdd Faild' temp.log
+ CHECK_RESULT 1 0 1 'load profile exist'
+ actual_result=1
+ expect_result=0
+ mode=1
+ error_log='load profile exist'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 1 -eq 0 ']'
+ test 1x == 0x
+ return 0
+ atune-adm list
failed to dial "/var/run/atuned/atuned.sock" : connection error: desc = "transport: error while dialing: dial unix /var/run/atuned/atuned.sock: connect: connection refused"
+ grep database-mysql-2p-sysbench-hdd temp.log
+ grep true
+ CHECK_RESULT 1 0 0 'ARRAY_PROFILE not found'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='ARRAY_PROFILE not found'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'ARRAY_PROFILE not found'
+ LOG_ERROR 'ARRAY_PROFILE not found'
+ message='ARRAY_PROFILE not found'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'ARRAY_PROFILE not found'
Thu May 25 23:09:24 2023 - ERROR - ARRAY_PROFILE not found
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_09.sh line 37'
+ message='oe_test_service_atuned_09.sh line 37'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_09.sh line 37'
Thu May 25 23:09:25 2023 - ERROR - oe_test_service_atuned_09.sh line 37
+ '[' 0 -eq 1 ']'
+ return 0
+ (( i++ ))
+ (( i<46 ))
+ atune-adm profile database-mysql-2p-sysbench-ssd
+ CHECK_RESULT 1 0 0 'atune-adm profile failure'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='atune-adm profile failure'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'atune-adm profile failure'
+ LOG_ERROR 'atune-adm profile failure'
+ message='atune-adm profile failure'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'atune-adm profile failure'
Thu May 25 23:09:26 2023 - ERROR - atune-adm profile failure
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_09.sh line 32'
+ message='oe_test_service_atuned_09.sh line 32'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_09.sh line 32'
Thu May 25 23:09:26 2023 - ERROR - oe_test_service_atuned_09.sh line 32
+ '[' 0 -eq 1 ']'
+ return 0
+ grep -i 'load profile database-mysql-2p-sysbench-ssd Faild' temp.log
+ CHECK_RESULT 1 0 1 'load profile exist'
+ actual_result=1
+ expect_result=0
+ mode=1
+ error_log='load profile exist'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 1 -eq 0 ']'
+ test 1x == 0x
+ return 0
+ atune-adm list
failed to dial "/var/run/atuned/atuned.sock" : connection error: desc = "transport: error while dialing: dial unix /var/run/atuned/atuned.sock: connect: connection refused"
+ grep database-mysql-2p-sysbench-ssd temp.log
+ grep true
+ CHECK_RESULT 1 0 0 'ARRAY_PROFILE not found'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='ARRAY_PROFILE not found'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'ARRAY_PROFILE not found'
+ LOG_ERROR 'ARRAY_PROFILE not found'
+ message='ARRAY_PROFILE not found'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'ARRAY_PROFILE not found'
Thu May 25 23:09:27 2023 - ERROR - ARRAY_PROFILE not found
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_09.sh line 37'
+ message='oe_test_service_atuned_09.sh line 37'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_09.sh line 37'
Thu May 25 23:09:28 2023 - ERROR - oe_test_service_atuned_09.sh line 37
+ '[' 0 -eq 1 ']'
+ return 0
+ (( i++ ))
+ (( i<46 ))
+ atune-adm profile database-postgresql-2p-sysbench-hdd
+ CHECK_RESULT 1 0 0 'atune-adm profile failure'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='atune-adm profile failure'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'atune-adm profile failure'
+ LOG_ERROR 'atune-adm profile failure'
+ message='atune-adm profile failure'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'atune-adm profile failure'
Thu May 25 23:09:29 2023 - ERROR - atune-adm profile failure
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_09.sh line 32'
+ message='oe_test_service_atuned_09.sh line 32'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_09.sh line 32'
Thu May 25 23:09:29 2023 - ERROR - oe_test_service_atuned_09.sh line 32
+ '[' 0 -eq 1 ']'
+ return 0
+ grep -i 'load profile database-postgresql-2p-sysbench-hdd Faild' temp.log
+ CHECK_RESULT 1 0 1 'load profile exist'
+ actual_result=1
+ expect_result=0
+ mode=1
+ error_log='load profile exist'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 1 -eq 0 ']'
+ test 1x == 0x
+ return 0
+ atune-adm list
failed to dial "/var/run/atuned/atuned.sock" : connection error: desc = "transport: error while dialing: dial unix /var/run/atuned/atuned.sock: connect: connection refused"
+ grep database-postgresql-2p-sysbench-hdd temp.log
+ grep true
+ CHECK_RESULT 1 0 0 'ARRAY_PROFILE not found'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='ARRAY_PROFILE not found'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'ARRAY_PROFILE not found'
+ LOG_ERROR 'ARRAY_PROFILE not found'
+ message='ARRAY_PROFILE not found'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'ARRAY_PROFILE not found'
Thu May 25 23:09:30 2023 - ERROR - ARRAY_PROFILE not found
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_09.sh line 37'
+ message='oe_test_service_atuned_09.sh line 37'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_09.sh line 37'
Thu May 25 23:09:31 2023 - ERROR - oe_test_service_atuned_09.sh line 37
+ '[' 0 -eq 1 ']'
+ return 0
+ (( i++ ))
+ (( i<46 ))
+ atune-adm profile database-postgresql-2p-sysbench-ssd
+ CHECK_RESULT 1 0 0 'atune-adm profile failure'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='atune-adm profile failure'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'atune-adm profile failure'
+ LOG_ERROR 'atune-adm profile failure'
+ message='atune-adm profile failure'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'atune-adm profile failure'
Thu May 25 23:09:31 2023 - ERROR - atune-adm profile failure
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_09.sh line 32'
+ message='oe_test_service_atuned_09.sh line 32'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_09.sh line 32'
Thu May 25 23:09:32 2023 - ERROR - oe_test_service_atuned_09.sh line 32
+ '[' 0 -eq 1 ']'
+ return 0
+ grep -i 'load profile database-postgresql-2p-sysbench-ssd Faild' temp.log
+ CHECK_RESULT 1 0 1 'load profile exist'
+ actual_result=1
+ expect_result=0
+ mode=1
+ error_log='load profile exist'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 1 -eq 0 ']'
+ test 1x == 0x
+ return 0
+ atune-adm list
failed to dial "/var/run/atuned/atuned.sock" : connection error: desc = "transport: error while dialing: dial unix /var/run/atuned/atuned.sock: connect: connection refused"
+ grep database-postgresql-2p-sysbench-ssd temp.log
+ grep true
+ CHECK_RESULT 1 0 0 'ARRAY_PROFILE not found'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='ARRAY_PROFILE not found'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'ARRAY_PROFILE not found'
+ LOG_ERROR 'ARRAY_PROFILE not found'
+ message='ARRAY_PROFILE not found'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'ARRAY_PROFILE not found'
Thu May 25 23:09:33 2023 - ERROR - ARRAY_PROFILE not found
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_09.sh line 37'
+ message='oe_test_service_atuned_09.sh line 37'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_09.sh line 37'
Thu May 25 23:09:33 2023 - ERROR - oe_test_service_atuned_09.sh line 37
+ '[' 0 -eq 1 ']'
+ return 0
+ (( i++ ))
+ (( i<46 ))
+ atune-adm profile default-default
+ CHECK_RESULT 1 0 0 'atune-adm profile failure'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='atune-adm profile failure'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'atune-adm profile failure'
+ LOG_ERROR 'atune-adm profile failure'
+ message='atune-adm profile failure'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'atune-adm profile failure'
Thu May 25 23:09:34 2023 - ERROR - atune-adm profile failure
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_09.sh line 32'
+ message='oe_test_service_atuned_09.sh line 32'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_09.sh line 32'
Thu May 25 23:09:35 2023 - ERROR - oe_test_service_atuned_09.sh line 32
+ '[' 0 -eq 1 ']'
+ return 0
+ grep -i 'load profile default-default Faild' temp.log
+ CHECK_RESULT 1 0 1 'load profile exist'
+ actual_result=1
+ expect_result=0
+ mode=1
+ error_log='load profile exist'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 1 -eq 0 ']'
+ test 1x == 0x
+ return 0
+ atune-adm list
failed to dial "/var/run/atuned/atuned.sock" : connection error: desc = "transport: error while dialing: dial unix /var/run/atuned/atuned.sock: connect: connection refused"
+ grep default-default temp.log
+ grep true
+ CHECK_RESULT 1 0 0 'ARRAY_PROFILE not found'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='ARRAY_PROFILE not found'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'ARRAY_PROFILE not found'
+ LOG_ERROR 'ARRAY_PROFILE not found'
+ message='ARRAY_PROFILE not found'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'ARRAY_PROFILE not found'
Thu May 25 23:09:35 2023 - ERROR - ARRAY_PROFILE not found
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_09.sh line 37'
+ message='oe_test_service_atuned_09.sh line 37'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_09.sh line 37'
Thu May 25 23:09:36 2023 - ERROR - oe_test_service_atuned_09.sh line 37
+ '[' 0 -eq 1 ']'
+ return 0
+ (( i++ ))
+ (( i<46 ))
+ atune-adm profile docker-mariadb-2p-tpcc-c3
+ CHECK_RESULT 1 0 0 'atune-adm profile failure'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='atune-adm profile failure'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'atune-adm profile failure'
+ LOG_ERROR 'atune-adm profile failure'
+ message='atune-adm profile failure'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'atune-adm profile failure'
Thu May 25 23:09:37 2023 - ERROR - atune-adm profile failure
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_09.sh line 32'
+ message='oe_test_service_atuned_09.sh line 32'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_09.sh line 32'
Thu May 25 23:09:37 2023 - ERROR - oe_test_service_atuned_09.sh line 32
+ '[' 0 -eq 1 ']'
+ return 0
+ grep -i 'load profile docker-mariadb-2p-tpcc-c3 Faild' temp.log
+ CHECK_RESULT 1 0 1 'load profile exist'
+ actual_result=1
+ expect_result=0
+ mode=1
+ error_log='load profile exist'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 1 -eq 0 ']'
+ test 1x == 0x
+ return 0
+ atune-adm list
failed to dial "/var/run/atuned/atuned.sock" : connection error: desc = "transport: error while dialing: dial unix /var/run/atuned/atuned.sock: connect: connection refused"
+ grep docker-mariadb-2p-tpcc-c3 temp.log
+ grep true
+ CHECK_RESULT 1 0 0 'ARRAY_PROFILE not found'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='ARRAY_PROFILE not found'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'ARRAY_PROFILE not found'
+ LOG_ERROR 'ARRAY_PROFILE not found'
+ message='ARRAY_PROFILE not found'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'ARRAY_PROFILE not found'
Thu May 25 23:09:38 2023 - ERROR - ARRAY_PROFILE not found
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_09.sh line 37'
+ message='oe_test_service_atuned_09.sh line 37'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_09.sh line 37'
Thu May 25 23:09:39 2023 - ERROR - oe_test_service_atuned_09.sh line 37
+ '[' 0 -eq 1 ']'
+ return 0
+ (( i++ ))
+ (( i<46 ))
+ atune-adm profile docker-mariadb-4p-tpcc-c3
+ CHECK_RESULT 1 0 0 'atune-adm profile failure'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='atune-adm profile failure'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'atune-adm profile failure'
+ LOG_ERROR 'atune-adm profile failure'
+ message='atune-adm profile failure'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'atune-adm profile failure'
Thu May 25 23:09:39 2023 - ERROR - atune-adm profile failure
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_09.sh line 32'
+ message='oe_test_service_atuned_09.sh line 32'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_09.sh line 32'
Thu May 25 23:09:40 2023 - ERROR - oe_test_service_atuned_09.sh line 32
+ '[' 0 -eq 1 ']'
+ return 0
+ grep -i 'load profile docker-mariadb-4p-tpcc-c3 Faild' temp.log
+ CHECK_RESULT 1 0 1 'load profile exist'
+ actual_result=1
+ expect_result=0
+ mode=1
+ error_log='load profile exist'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 1 -eq 0 ']'
+ test 1x == 0x
+ return 0
+ atune-adm list
failed to dial "/var/run/atuned/atuned.sock" : connection error: desc = "transport: error while dialing: dial unix /var/run/atuned/atuned.sock: connect: connection refused"
+ grep docker-mariadb-4p-tpcc-c3 temp.log
+ grep true
+ CHECK_RESULT 1 0 0 'ARRAY_PROFILE not found'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='ARRAY_PROFILE not found'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'ARRAY_PROFILE not found'
+ LOG_ERROR 'ARRAY_PROFILE not found'
+ message='ARRAY_PROFILE not found'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'ARRAY_PROFILE not found'
Thu May 25 23:09:41 2023 - ERROR - ARRAY_PROFILE not found
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_09.sh line 37'
+ message='oe_test_service_atuned_09.sh line 37'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_09.sh line 37'
Thu May 25 23:09:41 2023 - ERROR - oe_test_service_atuned_09.sh line 37
+ '[' 0 -eq 1 ']'
+ return 0
+ (( i++ ))
+ (( i<46 ))
+ atune-adm profile hpc-gatk4-human-genome
+ CHECK_RESULT 1 0 0 'atune-adm profile failure'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='atune-adm profile failure'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'atune-adm profile failure'
+ LOG_ERROR 'atune-adm profile failure'
+ message='atune-adm profile failure'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'atune-adm profile failure'
Thu May 25 23:09:42 2023 - ERROR - atune-adm profile failure
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_09.sh line 32'
+ message='oe_test_service_atuned_09.sh line 32'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_09.sh line 32'
Thu May 25 23:09:43 2023 - ERROR - oe_test_service_atuned_09.sh line 32
+ '[' 0 -eq 1 ']'
+ return 0
+ grep -i 'load profile hpc-gatk4-human-genome Faild' temp.log
+ CHECK_RESULT 1 0 1 'load profile exist'
+ actual_result=1
+ expect_result=0
+ mode=1
+ error_log='load profile exist'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 1 -eq 0 ']'
+ test 1x == 0x
+ return 0
+ atune-adm list
failed to dial "/var/run/atuned/atuned.sock" : connection error: desc = "transport: error while dialing: dial unix /var/run/atuned/atuned.sock: connect: connection refused"
+ grep hpc-gatk4-human-genome temp.log
+ grep true
+ CHECK_RESULT 1 0 0 'ARRAY_PROFILE not found'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='ARRAY_PROFILE not found'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'ARRAY_PROFILE not found'
+ LOG_ERROR 'ARRAY_PROFILE not found'
+ message='ARRAY_PROFILE not found'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'ARRAY_PROFILE not found'
Thu May 25 23:09:44 2023 - ERROR - ARRAY_PROFILE not found
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_09.sh line 37'
+ message='oe_test_service_atuned_09.sh line 37'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_09.sh line 37'
Thu May 25 23:09:44 2023 - ERROR - oe_test_service_atuned_09.sh line 37
+ '[' 0 -eq 1 ']'
+ return 0
+ (( i++ ))
+ (( i<46 ))
+ atune-adm profile in-memory-database-redis-redis-benchmark
+ CHECK_RESULT 1 0 0 'atune-adm profile failure'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='atune-adm profile failure'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'atune-adm profile failure'
+ LOG_ERROR 'atune-adm profile failure'
+ message='atune-adm profile failure'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'atune-adm profile failure'
Thu May 25 23:09:45 2023 - ERROR - atune-adm profile failure
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_09.sh line 32'
+ message='oe_test_service_atuned_09.sh line 32'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_09.sh line 32'
Thu May 25 23:09:45 2023 - ERROR - oe_test_service_atuned_09.sh line 32
+ '[' 0 -eq 1 ']'
+ return 0
+ grep -i 'load profile in-memory-database-redis-redis-benchmark Faild' temp.log
+ CHECK_RESULT 1 0 1 'load profile exist'
+ actual_result=1
+ expect_result=0
+ mode=1
+ error_log='load profile exist'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 1 -eq 0 ']'
+ test 1x == 0x
+ return 0
+ atune-adm list
failed to dial "/var/run/atuned/atuned.sock" : connection error: desc = "transport: error while dialing: dial unix /var/run/atuned/atuned.sock: connect: connection refused"
+ grep in-memory-database-redis-redis-benchmark temp.log
+ grep true
+ CHECK_RESULT 1 0 0 'ARRAY_PROFILE not found'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='ARRAY_PROFILE not found'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'ARRAY_PROFILE not found'
+ LOG_ERROR 'ARRAY_PROFILE not found'
+ message='ARRAY_PROFILE not found'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'ARRAY_PROFILE not found'
Thu May 25 23:09:46 2023 - ERROR - ARRAY_PROFILE not found
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_09.sh line 37'
+ message='oe_test_service_atuned_09.sh line 37'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_09.sh line 37'
Thu May 25 23:09:47 2023 - ERROR - oe_test_service_atuned_09.sh line 37
+ '[' 0 -eq 1 ']'
+ return 0
+ (( i++ ))
+ (( i<46 ))
+ atune-adm profile middleware-dubbo-dubbo-benchmark
+ CHECK_RESULT 1 0 0 'atune-adm profile failure'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='atune-adm profile failure'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'atune-adm profile failure'
+ LOG_ERROR 'atune-adm profile failure'
+ message='atune-adm profile failure'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'atune-adm profile failure'
Thu May 25 23:09:48 2023 - ERROR - atune-adm profile failure
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_09.sh line 32'
+ message='oe_test_service_atuned_09.sh line 32'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_09.sh line 32'
Thu May 25 23:09:48 2023 - ERROR - oe_test_service_atuned_09.sh line 32
+ '[' 0 -eq 1 ']'
+ return 0
+ grep -i 'load profile middleware-dubbo-dubbo-benchmark Faild' temp.log
+ CHECK_RESULT 1 0 1 'load profile exist'
+ actual_result=1
+ expect_result=0
+ mode=1
+ error_log='load profile exist'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 1 -eq 0 ']'
+ test 1x == 0x
+ return 0
+ atune-adm list
failed to dial "/var/run/atuned/atuned.sock" : connection error: desc = "transport: error while dialing: dial unix /var/run/atuned/atuned.sock: connect: connection refused"
+ grep middleware-dubbo-dubbo-benchmark temp.log
+ grep true
+ CHECK_RESULT 1 0 0 'ARRAY_PROFILE not found'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='ARRAY_PROFILE not found'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'ARRAY_PROFILE not found'
+ LOG_ERROR 'ARRAY_PROFILE not found'
+ message='ARRAY_PROFILE not found'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'ARRAY_PROFILE not found'
Thu May 25 23:09:49 2023 - ERROR - ARRAY_PROFILE not found
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_09.sh line 37'
+ message='oe_test_service_atuned_09.sh line 37'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_09.sh line 37'
Thu May 25 23:09:50 2023 - ERROR - oe_test_service_atuned_09.sh line 37
+ '[' 0 -eq 1 ']'
+ return 0
+ (( i++ ))
+ (( i<46 ))
+ atune-adm profile storage-ceph-vdbench-hdd
+ CHECK_RESULT 1 0 0 'atune-adm profile failure'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='atune-adm profile failure'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'atune-adm profile failure'
+ LOG_ERROR 'atune-adm profile failure'
+ message='atune-adm profile failure'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'atune-adm profile failure'
Thu May 25 23:09:50 2023 - ERROR - atune-adm profile failure
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_09.sh line 32'
+ message='oe_test_service_atuned_09.sh line 32'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_09.sh line 32'
Thu May 25 23:09:51 2023 - ERROR - oe_test_service_atuned_09.sh line 32
+ '[' 0 -eq 1 ']'
+ return 0
+ grep -i 'load profile storage-ceph-vdbench-hdd Faild' temp.log
+ CHECK_RESULT 1 0 1 'load profile exist'
+ actual_result=1
+ expect_result=0
+ mode=1
+ error_log='load profile exist'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 1 -eq 0 ']'
+ test 1x == 0x
+ return 0
+ atune-adm list
failed to dial "/var/run/atuned/atuned.sock" : connection error: desc = "transport: error while dialing: dial unix /var/run/atuned/atuned.sock: connect: connection refused"
+ grep storage-ceph-vdbench-hdd temp.log
+ grep true
+ CHECK_RESULT 1 0 0 'ARRAY_PROFILE not found'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='ARRAY_PROFILE not found'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'ARRAY_PROFILE not found'
+ LOG_ERROR 'ARRAY_PROFILE not found'
+ message='ARRAY_PROFILE not found'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'ARRAY_PROFILE not found'
Thu May 25 23:09:52 2023 - ERROR - ARRAY_PROFILE not found
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_09.sh line 37'
+ message='oe_test_service_atuned_09.sh line 37'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_09.sh line 37'
Thu May 25 23:09:52 2023 - ERROR - oe_test_service_atuned_09.sh line 37
+ '[' 0 -eq 1 ']'
+ return 0
+ (( i++ ))
+ (( i<46 ))
+ atune-adm profile storage-ceph-vdbench-ssd
+ CHECK_RESULT 1 0 0 'atune-adm profile failure'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='atune-adm profile failure'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'atune-adm profile failure'
+ LOG_ERROR 'atune-adm profile failure'
+ message='atune-adm profile failure'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'atune-adm profile failure'
Thu May 25 23:09:53 2023 - ERROR - atune-adm profile failure
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_09.sh line 32'
+ message='oe_test_service_atuned_09.sh line 32'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_09.sh line 32'
Thu May 25 23:09:54 2023 - ERROR - oe_test_service_atuned_09.sh line 32
+ '[' 0 -eq 1 ']'
+ return 0
+ grep -i 'load profile storage-ceph-vdbench-ssd Faild' temp.log
+ CHECK_RESULT 1 0 1 'load profile exist'
+ actual_result=1
+ expect_result=0
+ mode=1
+ error_log='load profile exist'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 1 -eq 0 ']'
+ test 1x == 0x
+ return 0
+ atune-adm list
failed to dial "/var/run/atuned/atuned.sock" : connection error: desc = "transport: error while dialing: dial unix /var/run/atuned/atuned.sock: connect: connection refused"
+ grep storage-ceph-vdbench-ssd temp.log
+ grep true
+ CHECK_RESULT 1 0 0 'ARRAY_PROFILE not found'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='ARRAY_PROFILE not found'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'ARRAY_PROFILE not found'
+ LOG_ERROR 'ARRAY_PROFILE not found'
+ message='ARRAY_PROFILE not found'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'ARRAY_PROFILE not found'
Thu May 25 23:09:55 2023 - ERROR - ARRAY_PROFILE not found
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_09.sh line 37'
+ message='oe_test_service_atuned_09.sh line 37'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_09.sh line 37'
Thu May 25 23:09:55 2023 - ERROR - oe_test_service_atuned_09.sh line 37
+ '[' 0 -eq 1 ']'
+ return 0
+ (( i++ ))
+ (( i<46 ))
+ atune-adm profile virtualization-consumer-cloud-olc
+ CHECK_RESULT 1 0 0 'atune-adm profile failure'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='atune-adm profile failure'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'atune-adm profile failure'
+ LOG_ERROR 'atune-adm profile failure'
+ message='atune-adm profile failure'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'atune-adm profile failure'
Thu May 25 23:09:56 2023 - ERROR - atune-adm profile failure
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_09.sh line 32'
+ message='oe_test_service_atuned_09.sh line 32'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_09.sh line 32'
Thu May 25 23:09:56 2023 - ERROR - oe_test_service_atuned_09.sh line 32
+ '[' 0 -eq 1 ']'
+ return 0
+ grep -i 'load profile virtualization-consumer-cloud-olc Faild' temp.log
+ CHECK_RESULT 1 0 1 'load profile exist'
+ actual_result=1
+ expect_result=0
+ mode=1
+ error_log='load profile exist'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 1 -eq 0 ']'
+ test 1x == 0x
+ return 0
+ atune-adm list
failed to dial "/var/run/atuned/atuned.sock" : connection error: desc = "transport: error while dialing: dial unix /var/run/atuned/atuned.sock: connect: connection refused"
+ grep virtualization-consumer-cloud-olc temp.log
+ grep true
+ CHECK_RESULT 1 0 0 'ARRAY_PROFILE not found'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='ARRAY_PROFILE not found'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'ARRAY_PROFILE not found'
+ LOG_ERROR 'ARRAY_PROFILE not found'
+ message='ARRAY_PROFILE not found'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'ARRAY_PROFILE not found'
Thu May 25 23:09:57 2023 - ERROR - ARRAY_PROFILE not found
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_09.sh line 37'
+ message='oe_test_service_atuned_09.sh line 37'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_09.sh line 37'
Thu May 25 23:09:58 2023 - ERROR - oe_test_service_atuned_09.sh line 37
+ '[' 0 -eq 1 ']'
+ return 0
+ (( i++ ))
+ (( i<46 ))
+ atune-adm profile virtualization-mariadb-2p-tpcc-c3
+ CHECK_RESULT 1 0 0 'atune-adm profile failure'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='atune-adm profile failure'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'atune-adm profile failure'
+ LOG_ERROR 'atune-adm profile failure'
+ message='atune-adm profile failure'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'atune-adm profile failure'
Thu May 25 23:09:58 2023 - ERROR - atune-adm profile failure
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_09.sh line 32'
+ message='oe_test_service_atuned_09.sh line 32'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_09.sh line 32'
Thu May 25 23:09:59 2023 - ERROR - oe_test_service_atuned_09.sh line 32
+ '[' 0 -eq 1 ']'
+ return 0
+ grep -i 'load profile virtualization-mariadb-2p-tpcc-c3 Faild' temp.log
+ CHECK_RESULT 1 0 1 'load profile exist'
+ actual_result=1
+ expect_result=0
+ mode=1
+ error_log='load profile exist'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 1 -eq 0 ']'
+ test 1x == 0x
+ return 0
+ atune-adm list
failed to dial "/var/run/atuned/atuned.sock" : connection error: desc = "transport: error while dialing: dial unix /var/run/atuned/atuned.sock: connect: connection refused"
+ grep virtualization-mariadb-2p-tpcc-c3 temp.log
+ grep true
+ CHECK_RESULT 1 0 0 'ARRAY_PROFILE not found'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='ARRAY_PROFILE not found'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'ARRAY_PROFILE not found'
+ LOG_ERROR 'ARRAY_PROFILE not found'
+ message='ARRAY_PROFILE not found'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'ARRAY_PROFILE not found'
Thu May 25 23:10:00 2023 - ERROR - ARRAY_PROFILE not found
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_09.sh line 37'
+ message='oe_test_service_atuned_09.sh line 37'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_09.sh line 37'
Thu May 25 23:10:00 2023 - ERROR - oe_test_service_atuned_09.sh line 37
+ '[' 0 -eq 1 ']'
+ return 0
+ (( i++ ))
+ (( i<46 ))
+ atune-adm profile virtualization-mariadb-4p-tpcc-c3
+ CHECK_RESULT 1 0 0 'atune-adm profile failure'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='atune-adm profile failure'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'atune-adm profile failure'
+ LOG_ERROR 'atune-adm profile failure'
+ message='atune-adm profile failure'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'atune-adm profile failure'
Thu May 25 23:10:01 2023 - ERROR - atune-adm profile failure
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_09.sh line 32'
+ message='oe_test_service_atuned_09.sh line 32'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_09.sh line 32'
Thu May 25 23:10:02 2023 - ERROR - oe_test_service_atuned_09.sh line 32
+ '[' 0 -eq 1 ']'
+ return 0
+ grep -i 'load profile virtualization-mariadb-4p-tpcc-c3 Faild' temp.log
+ CHECK_RESULT 1 0 1 'load profile exist'
+ actual_result=1
+ expect_result=0
+ mode=1
+ error_log='load profile exist'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 1 -eq 0 ']'
+ test 1x == 0x
+ return 0
+ atune-adm list
failed to dial "/var/run/atuned/atuned.sock" : connection error: desc = "transport: error while dialing: dial unix /var/run/atuned/atuned.sock: connect: connection refused"
+ grep virtualization-mariadb-4p-tpcc-c3 temp.log
+ grep true
+ CHECK_RESULT 1 0 0 'ARRAY_PROFILE not found'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='ARRAY_PROFILE not found'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'ARRAY_PROFILE not found'
+ LOG_ERROR 'ARRAY_PROFILE not found'
+ message='ARRAY_PROFILE not found'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'ARRAY_PROFILE not found'
Thu May 25 23:10:02 2023 - ERROR - ARRAY_PROFILE not found
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_09.sh line 37'
+ message='oe_test_service_atuned_09.sh line 37'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_09.sh line 37'
Thu May 25 23:10:03 2023 - ERROR - oe_test_service_atuned_09.sh line 37
+ '[' 0 -eq 1 ']'
+ return 0
+ (( i++ ))
+ (( i<46 ))
+ atune-adm profile web-apache-traffic-server-spirent-pingpo
+ CHECK_RESULT 1 0 0 'atune-adm profile failure'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='atune-adm profile failure'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'atune-adm profile failure'
+ LOG_ERROR 'atune-adm profile failure'
+ message='atune-adm profile failure'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'atune-adm profile failure'
Thu May 25 23:10:04 2023 - ERROR - atune-adm profile failure
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_09.sh line 32'
+ message='oe_test_service_atuned_09.sh line 32'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_09.sh line 32'
Thu May 25 23:10:04 2023 - ERROR - oe_test_service_atuned_09.sh line 32
+ '[' 0 -eq 1 ']'
+ return 0
+ grep -i 'load profile web-apache-traffic-server-spirent-pingpo Faild' temp.log
+ CHECK_RESULT 1 0 1 'load profile exist'
+ actual_result=1
+ expect_result=0
+ mode=1
+ error_log='load profile exist'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 1 -eq 0 ']'
+ test 1x == 0x
+ return 0
+ atune-adm list
failed to dial "/var/run/atuned/atuned.sock" : connection error: desc = "transport: error while dialing: dial unix /var/run/atuned/atuned.sock: connect: connection refused"
+ grep web-apache-traffic-server-spirent-pingpo temp.log
+ grep true
+ CHECK_RESULT 1 0 0 'ARRAY_PROFILE not found'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='ARRAY_PROFILE not found'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'ARRAY_PROFILE not found'
+ LOG_ERROR 'ARRAY_PROFILE not found'
+ message='ARRAY_PROFILE not found'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'ARRAY_PROFILE not found'
Thu May 25 23:10:05 2023 - ERROR - ARRAY_PROFILE not found
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_09.sh line 37'
+ message='oe_test_service_atuned_09.sh line 37'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_09.sh line 37'
Thu May 25 23:10:06 2023 - ERROR - oe_test_service_atuned_09.sh line 37
+ '[' 0 -eq 1 ']'
+ return 0
+ (( i++ ))
+ (( i<46 ))
+ atune-adm profile web-nginx-http-long-connection
+ CHECK_RESULT 1 0 0 'atune-adm profile failure'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='atune-adm profile failure'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'atune-adm profile failure'
+ LOG_ERROR 'atune-adm profile failure'
+ message='atune-adm profile failure'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'atune-adm profile failure'
Thu May 25 23:10:07 2023 - ERROR - atune-adm profile failure
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_09.sh line 32'
+ message='oe_test_service_atuned_09.sh line 32'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_09.sh line 32'
Thu May 25 23:10:07 2023 - ERROR - oe_test_service_atuned_09.sh line 32
+ '[' 0 -eq 1 ']'
+ return 0
+ grep -i 'load profile web-nginx-http-long-connection Faild' temp.log
+ CHECK_RESULT 1 0 1 'load profile exist'
+ actual_result=1
+ expect_result=0
+ mode=1
+ error_log='load profile exist'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 1 -eq 0 ']'
+ test 1x == 0x
+ return 0
+ atune-adm list
failed to dial "/var/run/atuned/atuned.sock" : connection error: desc = "transport: error while dialing: dial unix /var/run/atuned/atuned.sock: connect: connection refused"
+ grep web-nginx-http-long-connection temp.log
+ grep true
+ CHECK_RESULT 1 0 0 'ARRAY_PROFILE not found'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='ARRAY_PROFILE not found'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'ARRAY_PROFILE not found'
+ LOG_ERROR 'ARRAY_PROFILE not found'
+ message='ARRAY_PROFILE not found'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'ARRAY_PROFILE not found'
Thu May 25 23:10:08 2023 - ERROR - ARRAY_PROFILE not found
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_09.sh line 37'
+ message='oe_test_service_atuned_09.sh line 37'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_09.sh line 37'
Thu May 25 23:10:08 2023 - ERROR - oe_test_service_atuned_09.sh line 37
+ '[' 0 -eq 1 ']'
+ return 0
+ (( i++ ))
+ (( i<46 ))
+ atune-adm profile web-nginx-https-short-connection
+ CHECK_RESULT 1 0 0 'atune-adm profile failure'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='atune-adm profile failure'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'atune-adm profile failure'
+ LOG_ERROR 'atune-adm profile failure'
+ message='atune-adm profile failure'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'atune-adm profile failure'
Thu May 25 23:10:09 2023 - ERROR - atune-adm profile failure
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_09.sh line 32'
+ message='oe_test_service_atuned_09.sh line 32'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_09.sh line 32'
Thu May 25 23:10:10 2023 - ERROR - oe_test_service_atuned_09.sh line 32
+ '[' 0 -eq 1 ']'
+ return 0
+ grep -i 'load profile web-nginx-https-short-connection Faild' temp.log
+ CHECK_RESULT 1 0 1 'load profile exist'
+ actual_result=1
+ expect_result=0
+ mode=1
+ error_log='load profile exist'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 1 -eq 0 ']'
+ test 1x == 0x
+ return 0
+ atune-adm list
failed to dial "/var/run/atuned/atuned.sock" : connection error: desc = "transport: error while dialing: dial unix /var/run/atuned/atuned.sock: connect: connection refused"
+ grep web-nginx-https-short-connection temp.log
+ grep true
+ CHECK_RESULT 1 0 0 'ARRAY_PROFILE not found'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='ARRAY_PROFILE not found'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'ARRAY_PROFILE not found'
+ LOG_ERROR 'ARRAY_PROFILE not found'
+ message='ARRAY_PROFILE not found'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'ARRAY_PROFILE not found'
Thu May 25 23:10:10 2023 - ERROR - ARRAY_PROFILE not found
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_09.sh line 37'
+ message='oe_test_service_atuned_09.sh line 37'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_09.sh line 37'
Thu May 25 23:10:11 2023 - ERROR - oe_test_service_atuned_09.sh line 37
+ '[' 0 -eq 1 ']'
+ return 0
+ (( i++ ))
+ (( i<46 ))
+ atune-adm profile -h
+ grep 'active the specified profile and check the actived profile' temp.log
   atune-adm profile - active the specified profile and check the actived profile
+ CHECK_RESULT 0 0 0 'active the specified profile not found'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='active the specified profile not found'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ array=("$SPECIAL_CHARACTERS" "$ULTRA_LONG_CHARACTERS")
+ (( i=0 ))
+ (( i<2 ))
+ atune-adm profile '~\!@#%^*'
+ CHECK_RESULT 1 0 1 'atune-adm profile success'
+ actual_result=1
+ expect_result=0
+ mode=1
+ error_log='atune-adm profile success'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 1 -eq 0 ']'
+ test 1x == 0x
+ return 0
+ grep 'load profile .* Faild' temp.log
+ CHECK_RESULT 1 0 0 'load profile not found'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='load profile not found'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'load profile not found'
+ LOG_ERROR 'load profile not found'
+ message='load profile not found'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'load profile not found'
Thu May 25 23:10:12 2023 - ERROR - load profile not found
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_09.sh line 47'
+ message='oe_test_service_atuned_09.sh line 47'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_09.sh line 47'
Thu May 25 23:10:13 2023 - ERROR - oe_test_service_atuned_09.sh line 47
+ '[' 0 -eq 1 ']'
+ return 0
+ (( i++ ))
+ (( i<2 ))
+ atune-adm profile 0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
+ CHECK_RESULT 1 0 1 'atune-adm profile success'
+ actual_result=1
+ expect_result=0
+ mode=1
+ error_log='atune-adm profile success'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 1 -eq 0 ']'
+ test 1x == 0x
+ return 0
+ grep 'load profile .* Faild' temp.log
+ CHECK_RESULT 1 0 0 'load profile not found'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='load profile not found'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'load profile not found'
+ LOG_ERROR 'load profile not found'
+ message='load profile not found'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'load profile not found'
Thu May 25 23:10:14 2023 - ERROR - load profile not found
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_09.sh line 47'
+ message='oe_test_service_atuned_09.sh line 47'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_09.sh line 47'
Thu May 25 23:10:14 2023 - ERROR - oe_test_service_atuned_09.sh line 47
+ '[' 0 -eq 1 ']'
+ return 0
+ (( i++ ))
+ (( i<2 ))
+ atune-adm profile
+ grep 'only one workloadload type can be set' temp.log
only one workloadload type can be set
+ CHECK_RESULT 0 0 0 'only one workloadload type can be set not found'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='only one workloadload type can be set not found'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ CASE_RESULT 0
+ case_re=0
+ test -z 95
+ test 95 -gt 0
+ LOG_ERROR 'failed to execute the case.'
+ message='failed to execute the case.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'failed to execute the case.'
Thu May 25 23:10:15 2023 - ERROR - failed to execute the case.
+ exit 95
+ post_test
+ clean_autund
+ systemctl stop atuned
+ systemctl stop atune-engine
+ rm -fr /etc/atuned/atuned.cnf /etc/atuned/atuned.cnf
+ mv /etc/atuned/atuned.cnf.bak /etc/atuned/atuned.cnf
+ mv /etc/atuned/engine.cnf.bak /etc/atuned/engine.cnf
+ DNF_REMOVE
+ node=1
+ pkg_list=
+ mode=0
+ [[ -z /tmp/tmpntglxwoi ]]
+ '[' 0 -ne 0 ']'
+ '[' 1 == 0 ']'
+ python3 /root/mugen/libs/locallibs/rpm_manage.py remove --node 1 --pkgs '' --tempfile /tmp/tmpntglxwoi
+ '[' 0 -ne 0 ']'
+ rm -fr temp.log
