+ source /root/mugen/libs/locallibs/common_lib.sh
++ python3 --version
++ '[' 0 -eq 0 ']'
++ source /root/mugen/libs/locallibs/common_lib_python.sh
+ main
++ type -t post_test
+ '[' -n function ']'
+ trap post_test EXIT INT HUP TERM
+ rpm -qa
+ grep expect
++ type -t config_params
+ '[' -n '' ']'
++ type -t pre_test
+ '[' -n function ']'
+ pre_test
+ LOG_INFO 'Start to prepare the test environment.'
+ message='Start to prepare the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to prepare the test environment.'
Mon May 26 09:30:09 2025 - INFO  - Start to prepare the test environment.
+ DNF_INSTALL aide
+ pkgs=aide
+ node=1
+ '[' -z '' ']'
+ tmpfile=
++ python3 /root/mugen/libs/locallibs/rpm_manage.py install --pkgs aide --node 1 --tempfile ''
+ tmpfile2=/tmp/tmpaebs5h0m
+ '[' -z '' ']'
+ tmpfile=/tmp/tmpaebs5h0m
+ sed -i '$a/home DATAONLY' /etc/aide.conf
+ aide --init
Start timestamp: 2025-05-26 09:30:11 +0000 (AIDE 0.17.4)
AIDE initialized database at /var/lib/aide/aide.db.new.gz

Number of entries:	54785

---------------------------------------------------
The attributes of the (uncompressed) database(s):
---------------------------------------------------

/var/lib/aide/aide.db.new.gz
 MD5       : z+/NjBQbOnuDS0lco5KwqA==
 SHA1      : H2lemY3P9jV5h0wsvu2bdgIT9co=
 SHA256    : 1mKIlhIyPn2xZHLIgciUPMq1eGuX4bRC
             UuAO3lvyM5o=
 SHA512    : jecLygYUMRU1xmTH4eD3QDsuo6AMq7rm
             sS2NKCf3prV7PaXfxqUz9X/WZYA556GG
             EQFTZSYIMgsRTrqEovgJPQ==
 RMD160    : ApA+cdjl5l8UazBsWerJ5jwW2T8=
 TIGER     : 1B+BgYgl1FAoDTG+/ctN7cIR44QXK3BV
 CRC32     : Njltzw==
 WHIRLPOOL : 6n5F4w+ibP43chxeaX7yyBY06b1UeUIz
             +zRO1GPQfgDOHMk066i+0WMQc2Y4/l70
             kCziU8bksY9NBtbg5VZY8A==
 GOST      : tPtlTSwgluSqAHLKIdi/HtdTiN3ggy2E
             5T4TpKyVYDo=
 STRIBOG256: L/9Xlfbv7S8+JgLgDCrLtQaaJK8uZ2h7
             cbFd6R2UkrE=
 STRIBOG512: xM2qyqs/lIP1jYAwOZ6cirmsF1yv7nI9
             QnEpxjSewG83Uuhz6xTBJkD8Rf39N+2Q
             9qpuD8M4pN5GFiEUcgbgYA==
 SM3       : /+XsML1xHTsGuY6c4j4ZAIRBp0lJhisd
             zpLkkJzcfEo=


End timestamp: 2025-05-26 09:30:41 +0000 (run time: 0m 30s)
+ mv /var/lib/aide/aide.db.new.gz /var/lib/aide/aide.db.gz
+ LOG_INFO 'End to prepare the test environment.'
+ message='End to prepare the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End to prepare the test environment.'
Mon May 26 09:30:41 2025 - INFO  - End to prepare the test environment.
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ LOG_INFO 'Start to run test.'
+ message='Start to run test.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to run test.'
Mon May 26 09:30:41 2025 - INFO  - Start to run test.
+ sed -i '$a/errorconf' /etc/aide.conf
+ CHECK_RESULT 0 0 0 'Modify aide configuration items: failed!'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Modify aide configuration items: failed!'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ aide --config-check
+ grep -i Error
  ERROR: /etc/aide.conf:177: syntax error (line: '/errorconf')
+ CHECK_RESULT 0 0 0 'Check aide configuration contain error: failed!'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Check aide configuration contain error: failed!'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ sed -i '$d' /etc/aide.conf
+ CHECK_RESULT 0 0 0 'Delete aide configuration items: failed!'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Delete aide configuration items: failed!'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ aide --config-check
+ grep -i Error
+ CHECK_RESULT 1 1 0 'Check aide configuration not contain error: failed!'
+ actual_result=1
+ expect_result=1
+ mode=0
+ error_log='Check aide configuration not contain error: failed!'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 1x
+ return 0
+ LOG_INFO 'End to run test.'
+ message='End to run test.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End to run test.'
Mon May 26 09:30:41 2025 - INFO  - End to run test.
+ CASE_RESULT 0
+ case_re=0
+ test -z ''
+ test 0 -eq 0
+ LOG_INFO 'succeed to execute the case.'
+ message='succeed to execute the case.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'succeed to execute the case.'
Mon May 26 09:30:41 2025 - INFO  - succeed to execute the case.
+ exec_result=
+ exit 0
+ post_test
+ LOG_INFO 'Start to restore the test environment.'
+ message='Start to restore the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to restore the test environment.'
Mon May 26 09:30:41 2025 - INFO  - Start to restore the test environment.
+ DNF_REMOVE
+ node=1
+ pkg_list=
+ mode=0
+ [[ -z /tmp/tmpaebs5h0m ]]
+ '[' 0 -ne 0 ']'
+ '[' 1 == 0 ']'
+ python3 /root/mugen/libs/locallibs/rpm_manage.py remove --node 1 --pkgs '' --tempfile /tmp/tmpaebs5h0m
+ '[' 0 -ne 0 ']'
+ rm -rf /var/lib/aide
+ LOG_INFO 'End to restore the test environment.'
+ message='End to restore the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End to restore the test environment.'
Mon May 26 09:30:42 2025 - INFO  - End to restore the test environment.
