+ source ../common/common_lib.sh
++ source /root/mugen/libs/locallibs/common_lib.sh
+++ python3 --version
+++ '[' 0 -eq 0 ']'
+++ source /root/mugen/libs/locallibs/common_lib_python.sh
+ main
++ type -t post_test
+ '[' -n function ']'
+ trap post_test EXIT INT HUP TERM
+ rpm -qa
+ grep expect
++ type -t config_params
+ '[' -n '' ']'
++ type -t pre_test
+ '[' -n function ']'
+ pre_test
+ LOG_INFO 'Start environmental preparation.'
+ message='Start environmental preparation.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start environmental preparation.'
Tue Aug  8 20:22:30 2023 - INFO  - Start environmental preparation.
+ DNF_INSTALL gdm
+ pkgs=gdm
+ node=1
+ '[' -z '' ']'
+ tmpfile=
++ python3 /root/mugen/libs/locallibs/rpm_manage.py install --pkgs gdm --node 1 --tempfile ''
+ tmpfile2='Last metadata expiration check: 23:20:50 ago on Mon Aug  7 21:02:07 2023.
Error: 
 Problem: package gdm-1:43.0-1.oe2309.riscv64 requires gnome-shell, but none of the providers can be installed
  - conflicting requests
  - nothing provides gcr4(riscv-64) needed by gnome-shell-43.2-2.oe2309.riscv64
  - nothing provides libgcr-4.so.0.0.0()(64bit) needed by gnome-shell-43.2-2.oe2309.riscv64
  - nothing provides pipewire-gstreamer(riscv-64) needed by gnome-shell-43.2-2.oe2309.riscv64
(try to add '\''--skip-broken'\'' to skip uninstallable packages or '\''--nobest'\'' to use not only best candidate packages)'
+ '[' -z '' ']'
+ tmpfile='Last metadata expiration check: 23:20:50 ago on Mon Aug  7 21:02:07 2023.
Error: 
 Problem: package gdm-1:43.0-1.oe2309.riscv64 requires gnome-shell, but none of the providers can be installed
  - conflicting requests
  - nothing provides gcr4(riscv-64) needed by gnome-shell-43.2-2.oe2309.riscv64
  - nothing provides libgcr-4.so.0.0.0()(64bit) needed by gnome-shell-43.2-2.oe2309.riscv64
  - nothing provides pipewire-gstreamer(riscv-64) needed by gnome-shell-43.2-2.oe2309.riscv64
(try to add '\''--skip-broken'\'' to skip uninstallable packages or '\''--nobest'\'' to use not only best candidate packages)'
+ LOG_INFO 'End of environmental preparation!'
+ message='End of environmental preparation!'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End of environmental preparation!'
Tue Aug  8 20:22:59 2023 - INFO  - End of environmental preparation!
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ LOG_INFO 'Start testing...'
+ message='Start testing...'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start testing...'
Tue Aug  8 20:22:59 2023 - INFO  - Start testing...
+ test_execution gdm.service
+ service=gdm.service
++ date '+%Y-%m-%d %T'
+ log_time='2023-08-08 20:22:59'
+ test_restart gdm.service
+ service=gdm.service
+ systemctl restart gdm.service
Failed to restart gdm.service: Unit gdm.service not found.
+ CHECK_RESULT 5 0 0 'gdm.service restart failed'
+ actual_result=5
+ expect_result=0
+ mode=0
+ error_log='gdm.service restart failed'
+ exit_mode=0
+ '[' -z 5 ']'
+ '[' 0 -eq 0 ']'
+ test 5x '!=' 0x
+ test -n 'gdm.service restart failed'
+ LOG_ERROR 'gdm.service restart failed'
+ message='gdm.service restart failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'gdm.service restart failed'
Tue Aug  8 20:23:00 2023 - ERROR - gdm.service restart failed
+ (( exec_result++ ))
+ LOG_ERROR '../common/common_lib.sh line 34'
+ message='../common/common_lib.sh line 34'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message '../common/common_lib.sh line 34'
Tue Aug  8 20:23:00 2023 - ERROR - ../common/common_lib.sh line 34
+ '[' 0 -eq 1 ']'
+ return 0
+ SLEEP_WAIT 5
+ wait_time=5
+ cmd=
+ mode=1
+ python3 /root/mugen/libs/locallibs/sleep_wait.py --time 5 --cmd '' --mode 1
+ systemctl status gdm.service
+ grep 'Active: active'
Unit gdm.service could not be found.
+ CHECK_RESULT 1 0 0 'gdm.service restart failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='gdm.service restart failed'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'gdm.service restart failed'
+ LOG_ERROR 'gdm.service restart failed'
+ message='gdm.service restart failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'gdm.service restart failed'
Tue Aug  8 20:23:07 2023 - ERROR - gdm.service restart failed
+ (( exec_result++ ))
+ LOG_ERROR '../common/common_lib.sh line 37'
+ message='../common/common_lib.sh line 37'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message '../common/common_lib.sh line 37'
Tue Aug  8 20:23:07 2023 - ERROR - ../common/common_lib.sh line 37
+ '[' 0 -eq 1 ']'
+ return 0
+ systemctl stop gdm.service
Failed to stop gdm.service: Unit gdm.service not loaded.
+ CHECK_RESULT 5 0 0 'gdm.service stop failed'
+ actual_result=5
+ expect_result=0
+ mode=0
+ error_log='gdm.service stop failed'
+ exit_mode=0
+ '[' -z 5 ']'
+ '[' 0 -eq 0 ']'
+ test 5x '!=' 0x
+ test -n 'gdm.service stop failed'
+ LOG_ERROR 'gdm.service stop failed'
+ message='gdm.service stop failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'gdm.service stop failed'
Tue Aug  8 20:23:08 2023 - ERROR - gdm.service stop failed
+ (( exec_result++ ))
+ LOG_ERROR '../common/common_lib.sh line 39'
+ message='../common/common_lib.sh line 39'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message '../common/common_lib.sh line 39'
Tue Aug  8 20:23:09 2023 - ERROR - ../common/common_lib.sh line 39
+ '[' 0 -eq 1 ']'
+ return 0
+ SLEEP_WAIT 5
+ wait_time=5
+ cmd=
+ mode=1
+ python3 /root/mugen/libs/locallibs/sleep_wait.py --time 5 --cmd '' --mode 1
+ systemctl status gdm.service
+ grep 'Active: inactive'
Unit gdm.service could not be found.
+ CHECK_RESULT 1 0 0 'gdm.service stop failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='gdm.service stop failed'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'gdm.service stop failed'
+ LOG_ERROR 'gdm.service stop failed'
+ message='gdm.service stop failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'gdm.service stop failed'
Tue Aug  8 20:23:15 2023 - ERROR - gdm.service stop failed
+ (( exec_result++ ))
+ LOG_ERROR '../common/common_lib.sh line 42'
+ message='../common/common_lib.sh line 42'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message '../common/common_lib.sh line 42'
Tue Aug  8 20:23:15 2023 - ERROR - ../common/common_lib.sh line 42
+ '[' 0 -eq 1 ']'
+ return 0
+ systemctl start gdm.service
Failed to start gdm.service: Unit gdm.service not found.
+ CHECK_RESULT 5 0 0 'gdm.service start failed'
+ actual_result=5
+ expect_result=0
+ mode=0
+ error_log='gdm.service start failed'
+ exit_mode=0
+ '[' -z 5 ']'
+ '[' 0 -eq 0 ']'
+ test 5x '!=' 0x
+ test -n 'gdm.service start failed'
+ LOG_ERROR 'gdm.service start failed'
+ message='gdm.service start failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'gdm.service start failed'
Tue Aug  8 20:23:16 2023 - ERROR - gdm.service start failed
+ (( exec_result++ ))
+ LOG_ERROR '../common/common_lib.sh line 44'
+ message='../common/common_lib.sh line 44'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message '../common/common_lib.sh line 44'
Tue Aug  8 20:23:17 2023 - ERROR - ../common/common_lib.sh line 44
+ '[' 0 -eq 1 ']'
+ return 0
+ SLEEP_WAIT 5
+ wait_time=5
+ cmd=
+ mode=1
+ python3 /root/mugen/libs/locallibs/sleep_wait.py --time 5 --cmd '' --mode 1
+ systemctl status gdm.service
+ grep 'Active: active'
Unit gdm.service could not be found.
+ CHECK_RESULT 1 0 0 'gdm.service start failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='gdm.service start failed'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'gdm.service start failed'
+ LOG_ERROR 'gdm.service start failed'
+ message='gdm.service start failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'gdm.service start failed'
Tue Aug  8 20:23:23 2023 - ERROR - gdm.service start failed
+ (( exec_result++ ))
+ LOG_ERROR '../common/common_lib.sh line 47'
+ message='../common/common_lib.sh line 47'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message '../common/common_lib.sh line 47'
Tue Aug  8 20:23:24 2023 - ERROR - ../common/common_lib.sh line 47
+ '[' 0 -eq 1 ']'
+ return 0
+ test_enabled gdm.service
+ service=gdm.service
++ systemctl is-enabled gdm.service
Failed to get unit file state for gdm.service: No such file or directory
+ state=
+ '[' '' == enabled ']'
+ '[' '' == disabled ']'
+ '[' '' == masked ']'
+ '[' '' == static ']'
+ LOG_INFO 'Unit is indirect, ignoring.'
+ message='Unit is indirect, ignoring.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Unit is indirect, ignoring.'
Tue Aug  8 20:23:24 2023 - INFO  - Unit is indirect, ignoring.
+ journalctl --since '2023-08-08 20:22:59' -u gdm.service
+ grep -i 'fail\|error'
+ grep -v -i 'DEBUG\|INFO\|WARNING'
+ CHECK_RESULT 1 0 1 'There is an error message for the log of gdm.service'
+ actual_result=1
+ expect_result=0
+ mode=1
+ error_log='There is an error message for the log of gdm.service'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 1 -eq 0 ']'
+ test 1x == 0x
+ return 0
+ systemctl start gdm.service
Failed to start gdm.service: Unit gdm.service not found.
+ SLEEP_WAIT 5
+ wait_time=5
+ cmd=
+ mode=1
+ python3 /root/mugen/libs/locallibs/sleep_wait.py --time 5 --cmd '' --mode 1
+ sed -i 's\ExecStart=/usr/sbin/gdm\ExecStart=/usr/sbin/gdm --fatal-warnings\g' /usr/lib/systemd/system/gdm.service
sed: can't read /usr/lib/systemd/system/gdm.service: No such file or directory
+ systemctl daemon-reload
+ systemctl reload gdm.service
Failed to reload gdm.service: Unit gdm.service not found.
+ CHECK_RESULT 5 0 0 'gdm.service reload failed'
+ actual_result=5
+ expect_result=0
+ mode=0
+ error_log='gdm.service reload failed'
+ exit_mode=0
+ '[' -z 5 ']'
+ '[' 0 -eq 0 ']'
+ test 5x '!=' 0x
+ test -n 'gdm.service reload failed'
+ LOG_ERROR 'gdm.service reload failed'
+ message='gdm.service reload failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'gdm.service reload failed'
Tue Aug  8 20:23:32 2023 - ERROR - gdm.service reload failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_gdm.sh line 36'
+ message='oe_test_service_gdm.sh line 36'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_gdm.sh line 36'
Tue Aug  8 20:23:33 2023 - ERROR - oe_test_service_gdm.sh line 36
+ '[' 0 -eq 1 ']'
+ return 0
+ systemctl status gdm.service
+ grep 'Active: active'
Unit gdm.service could not be found.
+ CHECK_RESULT 1 0 0 'gdm.service reload causes the service status to change'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='gdm.service reload causes the service status to change'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'gdm.service reload causes the service status to change'
+ LOG_ERROR 'gdm.service reload causes the service status to change'
+ message='gdm.service reload causes the service status to change'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'gdm.service reload causes the service status to change'
Tue Aug  8 20:23:34 2023 - ERROR - gdm.service reload causes the service status to change
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_gdm.sh line 38'
+ message='oe_test_service_gdm.sh line 38'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_gdm.sh line 38'
Tue Aug  8 20:23:34 2023 - ERROR - oe_test_service_gdm.sh line 38
+ '[' 0 -eq 1 ']'
+ return 0
+ LOG_INFO 'Finish test!'
+ message='Finish test!'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Finish test!'
Tue Aug  8 20:23:35 2023 - INFO  - Finish test!
+ CASE_RESULT 0
+ case_re=0
+ test -z 8
+ test 8 -gt 0
+ LOG_ERROR 'failed to execute the case.'
+ message='failed to execute the case.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'failed to execute the case.'
Tue Aug  8 20:23:35 2023 - ERROR - failed to execute the case.
+ exit 8
+ post_test
+ LOG_INFO 'start environment cleanup.'
+ message='start environment cleanup.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'start environment cleanup.'
Tue Aug  8 20:23:36 2023 - INFO  - start environment cleanup.
+ sed -i 's\ExecStart=/usr/sbin/gdm --fatal-warnings\ExecStart=/usr/sbin/gdm\g' /usr/lib/systemd/system/gdm.service
sed: can't read /usr/lib/systemd/system/gdm.service: No such file or directory
+ systemctl daemon-reload
+ systemctl reload gdm.service
Failed to reload gdm.service: Unit gdm.service not found.
+ DNF_REMOVE
+ node=1
+ pkg_list=
+ mode=0
+ [[ -z Last metadata expiration check: 23:20:50 ago on Mon Aug  7 21:02:07 2023.
Error: 
 Problem: package gdm-1:43.0-1.oe2309.riscv64 requires gnome-shell, but none of the providers can be installed
  - conflicting requests
  - nothing provides gcr4(riscv-64) needed by gnome-shell-43.2-2.oe2309.riscv64
  - nothing provides libgcr-4.so.0.0.0()(64bit) needed by gnome-shell-43.2-2.oe2309.riscv64
  - nothing provides pipewire-gstreamer(riscv-64) needed by gnome-shell-43.2-2.oe2309.riscv64
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages) ]]
+ '[' 0 -ne 0 ']'
+ '[' 1 == 0 ']'
+ python3 /root/mugen/libs/locallibs/rpm_manage.py remove --node 1 --pkgs '' --tempfile 'Last metadata expiration check: 23:20:50 ago on Mon Aug  7 21:02:07 2023.
Error: 
 Problem: package gdm-1:43.0-1.oe2309.riscv64 requires gnome-shell, but none of the providers can be installed
  - conflicting requests
  - nothing provides gcr4(riscv-64) needed by gnome-shell-43.2-2.oe2309.riscv64
  - nothing provides libgcr-4.so.0.0.0()(64bit) needed by gnome-shell-43.2-2.oe2309.riscv64
  - nothing provides pipewire-gstreamer(riscv-64) needed by gnome-shell-43.2-2.oe2309.riscv64
(try to add '\''--skip-broken'\'' to skip uninstallable packages or '\''--nobest'\'' to use not only best candidate packages)'
Traceback (most recent call last):
  File "/root/mugen/libs/locallibs/rpm_manage.py", line 192, in <module>
    exitcode = rpm_remove(args.node, args.pkgs, args.tempfile)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/mugen/libs/locallibs/rpm_manage.py", line 163, in rpm_remove
    with open(tmpfile, "r") as f:
         ^^^^^^^^^^^^^^^^^^
OSError: [Errno 36] File name too long: "Last metadata expiration check: 23:20:50 ago on Mon Aug  7 21:02:07 2023.\nError: \n Problem: package gdm-1:43.0-1.oe2309.riscv64 requires gnome-shell, but none of the providers can be installed\n  - conflicting requests\n  - nothing provides gcr4(riscv-64) needed by gnome-shell-43.2-2.oe2309.riscv64\n  - nothing provides libgcr-4.so.0.0.0()(64bit) needed by gnome-shell-43.2-2.oe2309.riscv64\n  - nothing provides pipewire-gstreamer(riscv-64) needed by gnome-shell-43.2-2.oe2309.riscv64\n(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)"
+ '[' 0 -ne 0 ']'
+ LOG_INFO 'Finish environment cleanup!'
+ message='Finish environment cleanup!'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Finish environment cleanup!'
Tue Aug  8 20:23:41 2023 - INFO  - Finish environment cleanup!
